capacity4dev/capacity4more

capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/controllers/drupalForm.js
capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/controllers/main.js
capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/services/quick-post.js

Fix "ESC" close popups for taxonomy.

---

capacity4more/modules/c4m/restful/c4m_restful/plugins/restful/node/events/1.0/C4mRestfulEventsResource.class.php
capacity4more/modules/c4m/restful/c4m_restful_quick_post/c4m_restful_quick_post.module
capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/controllers/drupalForm.js
capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/controllers/main.js
capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/directives/calendar/calendar.html
capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/services/request.js
capacity4more/modules/c4m/restful/c4m_restful_quick_post/templates/quick-post-form.tpl.php

Error creating event in full form

---

capacity4more/modules/c4m/og/c4m_og_vocab/c4m_og_vocab.module
capacity4more/modules/c4m/vocab/c4m_vocab_widget/c4m_vocab_widget.module
capacity4more/modules/c4m/widgets/c4m_document_widget/c4m_document_widget.module
capacity4more/themes/c4m/kapablo/sass/base/_fields.scss

Error in tags on validation page.

---

capacity4more/modules/c4m/og/c4m_og_vocab/c4m_og_vocab.module
capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/controllers/drupalForm.js
capacity4more/modules/c4m/vocab/c4m_vocab_widget/c4m_vocab_widget.module

WIP: Show selected taxonomy

---

capacity4more/modules/c4m/og/c4m_og_vocab/c4m_og_vocab.module
capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/controllers/drupalForm.js
capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/directives/list-terms/list-terms.js
capacity4more/modules/c4m/vocab/c4m_vocab_widget/c4m_vocab_widget.module
capacity4more/modules/c4m/vocab/c4m_vocab_widget/templates/c4m_vocab_widget.tpl.php
capacity4more/modules/c4m/widgets/c4m_document_widget/c4m_document_widget.module

Taxonomy filter.

---

capacity4more/modules/c4m/restful/c4m_restful/plugins/restful/C4mRestfulEntityBaseNode.class.php

#356 
@amitaibu This PR is ready for code review.

Error while creating new tags in quick post

---

capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/controllers/drupalForm.js
capacity4more/modules/c4m/restful/c4m_restful_quick_post/templates/quick-post-form.tpl.php
capacity4more/themes/c4m/kapablo/sass/components/_forms.scss

Uncheck children terms when parent term is unchecked.

---

capacity4more/modules/c4m/widgets/c4m_document_widget/c4m_document_widget.module
capacity4more/modules/c4m/widgets/c4m_document_widget/templates/c4m_document_widget.tpl.php

Show document field title.

---

capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/controllers/drupalForm.js
capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/controllers/main.js

CFD-248 : Close popup box when "esc" is pressed or click outside popup box

---

capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/controllers/drupalForm.js
capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/controllers/main.js
capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/directives/list-terms/list-terms.html
capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/directives/list-terms/list-terms.js
capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/services/quick-post.js
capacity4more/modules/c4m/restful/c4m_restful_quick_post/templates/quick-post-form.tpl.php
capacity4more/modules/c4m/vocab/c4m_vocab_widget/c4m_vocab_widget.module
capacity4more/modules/c4m/vocab/c4m_vocab_widget/templates/c4m_vocab_widget.tpl.php

CFD-206 : Regions & Country widget should have 3 levels.

---

capacity4more/modules/c4m/restful/c4m_restful/plugins/restful/C4mRestfulEntityBaseNode.class.php
capacity4more/modules/c4m/restful/c4m_restful_quick_post/plugins/content_types/quick_form/quick_form.inc

CFD-262 : BLOCKER: Fixed loading dashboard.

---

.travis.yml
capacity4more/behat/travis-ci.config.sh

I also fixed the download URL of the tika jar file.

CI : Upgrade Tika to v1.7

---

capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/controllers/main.js
capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/services/quick-post.js

CFD-255 : Quick Post : not working in a newly created group 

---

capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/controllers/main.js
capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/filters/terms-filter.js
capacity4more/modules/c4m/restful/c4m_restful_quick_post/templates/quick-post-form.tpl.php

CFD-268 : Quick Post : Add option to replace the uploaded file 

---

capacity4more/modules/c4m/restful/c4m_restful_quick_post/c4m_restful_quick_post.module

PR for issue https://issuetracker.amplexor.com/jira/browse/CFD-273

CFD-273 : Drag n drop on event form broke

---

capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/directives/documents/documents.html
capacity4more/modules/c4m/restful/c4m_restful_quick_post/templates/quick-post-form.tpl.php
capacity4more/themes/c4m/kapablo/sass/components/_menu.scss

PR for issue https://issuetracker.amplexor.com/jira/browse/CFD-275

CFD-275 : Missing the image missing_icon.png on group dashboard

---

capacity4more/modules/c4m/restful/c4m_restful_quick_post/templates/quick-post-form.tpl.php
capacity4more/themes/c4m/kapablo/sass/components/_forms.scss

CFD-279 : File Widget : Dropzone to replace an uploaded file should be larger

---

capacity4more/modules/c4m/restful/c4m_restful/plugins/restful/node/documents/1.0/C4mRestfulDocumentsResource.class.php

CFD-280 : File widget : Error from restful when uploading a file 

---

capacity4more/modules/c4m/content/c4m_content_group/c4m_content_group.features.field_instance.inc
capacity4more/modules/c4m/content/c4m_content_group/c4m_content_group.info
capacity4more/modules/c4m/content/c4m_content_group/c4m_content_group.strongarm.inc

CFD-253 : Create Group : Fix the order of the fields 

---

capacity4more/modules/c4m/og/c4m_og_vocab/templates/c4m_categories_vocab_widget.tpl.php
capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/controllers/drupalForm.js
capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/controllers/main.js
capacity4more/modules/c4m/restful/c4m_restful_quick_post/templates/quick-post-form.tpl.php
capacity4more/modules/c4m/vocab/c4m_vocab_widget/templates/c4m_vocab_widget.tpl.php

CFD-274 : Geo widget : Add arrow logic for 3rd level 

---

capacity4more/themes/c4m/kapablo/js/kapablo_overlay.js
capacity4more/themes/c4m/kapablo/kapablo.info

CFD-281 : Vertical tabs are broken 

---

capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/directives/documents/documents.html
capacity4more/themes/c4m/kapablo/package.json
capacity4more/themes/c4m/kapablo/sass/components/_forms.scss

There were some dependencies (geo widget). Themed them now that these issues have been merged in.

CFD-190 : Theming dependencies

---

capacity4more/capacity4more.install
capacity4more/modules/c4m/restful/c4m_restful_quick_post/c4m_restful_quick_post.module

CFD-276 : Quick Post : Creation of discussion through quick post caused errors for non-admin

---

capacity4more/drupal-org.make

See #310
Added patched to fix the error while deleting group nodes.

CFD-277 : Error when trying to delete a group node

---

capacity4more/capacity4more.install

Activity stream : Show more button for non-logged-in users.

---

capacity4more/capacity4more.profile
capacity4more/modules/c4m/widgets/c4m_document_widget/c4m_document_widget.module

The kapablo theme does not fully support all backend modules (eg features, views, …).
This breaks the interface for the developers.
I made sure that the pages regarding to the document widget have the kapablo theme.

Restored seven theme as administration theme.

---

capacity4more/themes/c4m/kapablo/sass/components/_homepage.scss
capacity4more/themes/c4m/kapablo/sass/style.scss
jekyll/app/_scss/main.scss

CFD-286 Homepage : Featured block - Theming

---

capacity4more/modules/c4m/content/c4m_content_event/c4m_content_event.ds.inc
capacity4more/modules/c4m/content/c4m_content_event/c4m_content_event.features.field_instance.inc
capacity4more/modules/c4m/features/c4m_features_homepage/plugins/content_types/c4m_suggested_groups/c4m_suggested_groups.inc
capacity4more/modules/c4m/features_og/c4m_features_og_events/c4m_features_og_events.module
capacity4more/modules/c4m/features_og/c4m_features_og_events/plugins/content_types/upcoming_events/upcoming_events.inc
capacity4more/modules/c4m/features_og/c4m_features_og_events/plugins/content_types/upcoming_events/upcoming_events.tpl.php
capacity4more/themes/c4m/kapablo/sass/components/_group_blocks.scss
capacity4more/themes/c4m/kapablo/sass/components/_views.scss

CFD-298 : Homepage : Upcoming events - Theming

---

capacity4more/modules/c4m/content/c4m_content_featured/c4m_content_featured.features.field_instance.inc

See #516
Made the link field mandatory for featured content items.

CFD-286 : Homepage : Featured block - Fatal error when no link set

---

capacity4more/modules/c4m/features/c4m_features_homepage/c4m_features_homepage.pages_default.inc

CFD-294 : Homepage : My Groups is missing

---

capacity4more/modules/c4m/features/c4m_features_homepage/plugins/content_types/my_groups/my_groups.inc

CFD-294 : Homepage : Shows My groups block when no groups found.

---

README.md

Add a unit test section to README file

---

capacity4more/themes/c4m/kapablo/sass/components/_facets.scss
capacity4more/themes/c4m/kapablo/sass/components/_icon.scss
capacity4more/themes/c4m/kapablo/theme/preprocess.inc

CFD-366: Themed restricted group type on group overview

---

capacity4more/modules/c4m/content/c4m_content_group/c4m_content_group.module
capacity4more/modules/c4m/demo/c4m_demo_content/includes/CreateOgGroups.inc

#568
* First commit for https://github.com/capacity4dev/capacity4more/pull/550/files#r27391678

CFD-412: Group Approval Workflow : Update migration

---

capacity4more/themes/c4m/kapablo/theme/menu.inc

Fix wiki dropdown on group dashboard

---

capacity4more/drupal-org.make
capacity4more/modules/c4m/features_og/c4m_features_og_discussions/c4m_features_og_discussions.install
capacity4more/modules/c4m/features_og/c4m_features_og_discussions/c4m_features_og_discussions.module
capacity4more/modules/c4m/features_og/c4m_features_og_discussions/c4m_features_og_discussions.views_default.inc
capacity4more/modules/c4m/features_og/c4m_features_og_documents/c4m_features_og_documents.install
capacity4more/modules/c4m/features_og/c4m_features_og_documents/c4m_features_og_documents.module
capacity4more/modules/c4m/features_og/c4m_features_og_documents/c4m_features_og_documents.views_default.inc
capacity4more/modules/c4m/features_og/c4m_features_og_events/c4m_features_og_events.install
capacity4more/modules/c4m/features_og/c4m_features_og_events/c4m_features_og_events.module
capacity4more/modules/c4m/features_og/c4m_features_og_events/c4m_features_og_events.views_default.inc
capacity4more/modules/c4m/features_og/c4m_features_og_group_dashboard/c4m_features_og_group_dashboard.install
capacity4more/modules/c4m/features_og/c4m_features_og_group_dashboard/c4m_features_og_group_dashboard.module
capacity4more/modules/c4m/features_og/c4m_features_og_members/c4m_features_og_members.install
capacity4more/modules/c4m/features_og/c4m_features_og_members/c4m_features_og_members.module
capacity4more/modules/c4m/features_og/c4m_features_og_members/c4m_features_og_members.views_default.inc
capacity4more/modules/c4m/features_og/c4m_features_og_tasklists/c4m_features_og_tasklists.info
capacity4more/modules/c4m/features_og/c4m_features_og_tasklists/c4m_features_og_tasklists.install
capacity4more/modules/c4m/features_og/c4m_features_og_tasklists/c4m_features_og_tasklists.module
capacity4more/modules/c4m/features_og/c4m_features_og_tasklists/c4m_features_og_tasklists.views_default.inc
capacity4more/modules/c4m/features_og/c4m_features_og_wiki/c4m_features_og_wiki.info
capacity4more/modules/c4m/features_og/c4m_features_og_wiki/c4m_features_og_wiki.install
capacity4more/modules/c4m/features_og/c4m_features_og_wiki/c4m_features_og_wiki.module
capacity4more/modules/c4m/og/c4m_og/c4m_og.api.php
capacity4more/modules/c4m/og/c4m_og/c4m_og.info
capacity4more/modules/c4m/og/c4m_og/c4m_og.install
capacity4more/modules/c4m/og/c4m_og/c4m_og.module
capacity4more/modules/c4m/og/c4m_og/c4m_og.variable.inc
capacity4more/modules/c4m/og/c4m_og/c4m_og_access_plugin.inc
capacity4more/modules/c4m/user/c4m_user_profile/c4m_user_profile.module

The group views have been extended with a form to select what feature should be enabled.
All group features now use this plugin.

CFD-401 manage group features views access plugin

---

capacity4more/modules/c4m/features_og/c4m_features_og_manage/c4m_manage_categories.inc
capacity4more/modules/c4m/features_og/c4m_features_og_manage/js/taxonomy.js
capacity4more/themes/c4m/kapablo/sass/components/_forms.scss

WIP. CFD-388 : Group management Categories : Reorder Category terms.

---

capacity4more/modules/c4m/features_og/c4m_features_og_manage/c4m_manage_categories.inc
capacity4more/modules/c4m/features_og/c4m_features_og_manage/js/taxonomy.js
capacity4more/modules/c4m/restful/c4m_restful/plugins/restful/taxonomy_term/categories/1.0/RestfulEntityTaxonomyTermCategories.class.php
capacity4more/modules/c4m/restful/c4m_restful_quick_post/c4m_restful_quick_post.module
capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/controllers/add-term.js
capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/services/entity.js
capacity4more/themes/c4m/kapablo/sass/components/_taxonomy_form.scss

CFD-387 : Group management Categories : Add/Update/Delete Category terms.

---

capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/controllers/main.js
capacity4more/themes/c4m/kapablo/sass/components/_quickpost.scss

CFD-339 expand editor window does not function 

---

capacity4more/modules/c4m/message/c4m_message/c4m_message.module
capacity4more/modules/c4m/restful/c4m_restful/plugins/restful/node/activity_stream/1.0/C4mRestfulActivityStreamResource.class.php

CFD-410: Activity stream: Do not show unpublished content

---

capacity4more/behat/features/bootstrap/FeatureContext/Homepage.php
capacity4more/behat/features/homepage.feature
capacity4more/themes/c4m/kapablo/sass/components/_group_blocks.scss

Tests: Add new behat tests for the new features in the homepage.

---

capacity4more/modules/c4m/features/c4m_features_homepage/c4m_features_homepage.module
capacity4more/modules/c4m/features/c4m_features_homepage/templates/voices-views-carousel.tpl.php
capacity4more/themes/c4m/kapablo/sass/components/_carousel.scss

CFD-418: Voices & Views carousel : missing creation date

---

capacity4more/modules/c4m/content/c4m_content_event/c4m_content_event.ds.inc
capacity4more/modules/c4m/content/c4m_content_event/c4m_content_event.features.field_instance.inc

Added stats to event teaser, removed default links.

CFD-328 Event overview stats

---

capacity4more/modules/c4m/content/c4m_content_event/c4m_content_event.features.field_instance.inc
capacity4more/modules/c4m/content/c4m_content_event/c4m_content_event.field_group.inc
capacity4more/modules/c4m/content/c4m_content_event/c4m_content_event.strongarm.inc

Fixed the label for the Topics.

CFD-333 : Event creation form fixed fieldset & label

---

capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/services/quick-post.js

#608 
Selecting past date:
Created event with past dates:

CFD-332 : Cannot select past date in QP event.

---

capacity4more/themes/c4m/kapablo/sass/components/_group_blocks.scss

CFD-327: Set fieldset height on auto in group details

---

capacity4more/modules/c4m/restful/c4m_restful_quick_post/c4m_restful_quick_post.module
capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/controllers/main.js
capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/services/quick-post.js
capacity4more/themes/c4m/kapablo/sass/components/_activity_steam.scss

#649 
Workflow of disabling and enabling features and the effect on quick post:

CFD-405 : Manage Group features : Quick post

---

capacity4more/behat/features/bootstrap/FeatureContext/Group.php
capacity4more/behat/features/group_features.feature

Added Behat tests scenario's:
- Check I can manage features as group owner.
- Check I can't manage features as group member.
- Check I can disable features as group owner.
- Check I can enable features as group owner.

CFD-401 Manage group features

---

capacity4more/modules/c4m/content/c4m_content_group/c4m_content_group.module

https://issuetracker.amplexor.com/jira/browse/CFD-433

CFD-433 Request a group : The theme for this page should be kapablo, not seven

---

capacity4more/behat/features/group_documents.feature
capacity4more/modules/c4m/features_og/c4m_features_og_documents/c4m_features_og_documents.views_default.inc

added create document button
updated title of search to browse

CFD-341 Create document button in library

---

capacity4more/behat/composer.lock
capacity4more/behat/features/activity_stream.feature
capacity4more/behat/features/bootstrap/FeatureContext/Activity.php
capacity4more/behat/features/homepage.feature
capacity4more/modules/c4m/message/c4m_message/plugins/content_types/activity_stream/activity-stream.tpl.php

CFD-330 : Display full name in messages (activity stream) - Fix tests

---

capacity4more/modules/c4m/user/c4m_user/includes/c4m_user.theme.inc
capacity4more/themes/c4m/kapablo/sass/components/_views.scss

Display Anonymous as 'username' on nodes that are created by anonymous (uid=0) and rendered with 'User first and last name linked to profile' field formatter

CFD-358 select date filter generates error message

---

capacity4more/modules/c4m/features/c4m_features_homepage/c4m_features_homepage.module

https://issuetracker.amplexor.com/jira/browse/CFD-459

CFD-459 : V&V carrousel missing date

---

capacity4more/modules/c4m/features_og/c4m_features_og_members/c4m_features_og_members.context.inc

hide article carousel on group member overviews

CFD-456 Group Member overview displays V&V promo box

---

capacity4more/behat/features/bootstrap/FeatureContext/Homepage.php
capacity4more/modules/c4m/features/c4m_features_homepage/c4m_features_homepage.module
capacity4more/modules/c4m/features/c4m_features_homepage/templates/voices-views-carousel.tpl.php

https://issuetracker.amplexor.com/jira/browse/CFD-458

CFD-458 : V&V carousel items are not hyperlinked

---

capacity4more/modules/c4m/features/c4m_features_overview_events/c4m_features_overview_events.module
capacity4more/modules/c4m/features_og/c4m_features_og_events/c4m_features_og_events.module

CFD-493 Fixed search breadcrumb on event overviews

---

capacity4more/modules/c4m/content/c4m_content_group/c4m_content_group.features.field_instance.inc

fixed typo: "Please provide a brief description of the objectives and scope of this group."

CFD-439 fixed typo

---

capacity4more/modules/c4m/content/c4m_content_document/c4m_content_document.features.field_instance.inc

added new document types to upload: pps ppt pptx odt ods odp odf gif pdt pdtx vsd zip

CFD-448 accepted file types

---

capacity4more/modules/c4m/features/c4m_features_overview_people/c4m_features_overview_people.views_default.inc
capacity4more/modules/c4m/features_og/c4m_features_og_members/c4m_features_og_members.views_default.inc
capacity4more/themes/c4m/kapablo/sass/components/_members.scss
capacity4more/themes/c4m/kapablo/sass/components/_people.scss

Filtered blocked/not active users, removing empty lines
CSS line-height

CFD-442 : Bugged table display

---

capacity4more/modules/c4m/features_og/c4m_features_og_events/plugins/content_types/upcoming_events/upcoming_events.tpl.php

CFD-479 link to event overview

---

capacity4more/modules/c4m/features/c4m_features_overview_articles/c4m_features_overview_articles.views_default.inc
capacity4more/modules/c4m/features/c4m_features_overview_events/c4m_features_overview_events.views_default.inc
capacity4more/modules/c4m/features/c4m_features_overview_groups/c4m_features_overview_groups.views_default.inc
capacity4more/modules/c4m/features/c4m_features_overview_people/c4m_features_overview_people.views_default.inc
capacity4more/modules/c4m/features/c4m_features_overview_projects/c4m_features_overview_projects.views_default.inc
capacity4more/modules/c4m/features/c4m_features_overview_topics/c4m_features_overview_topics.views_default.inc
capacity4more/modules/c4m/features_og/c4m_features_og_discussions/c4m_features_og_discussions.views_default.inc
capacity4more/modules/c4m/features_og/c4m_features_og_documents/c4m_features_og_documents.views_default.inc
capacity4more/modules/c4m/features_og/c4m_features_og_events/c4m_features_og_events.views_default.inc
capacity4more/modules/c4m/features_og/c4m_features_og_members/c4m_features_og_members.views_default.inc
capacity4more/modules/c4m/features_og/c4m_features_og_tasklists/c4m_features_og_tasklists.views_default.inc
capacity4more/themes/c4m/kapablo/sass/components/_pager.scss
capacity4more/themes/c4m/kapablo/theme/pager.inc

CFD-473 missing first last pagination

---

capacity4more/capacity4more.install
capacity4more/modules/c4m/content/c4m_content_event/c4m_content_event.ds.inc
capacity4more/themes/c4m/kapablo/sass/base/_fields.scss
capacity4more/themes/c4m/kapablo/sass/components/_event.scss
capacity4more/themes/c4m/kapablo/sass/components/_forms.scss

CFD-487 Fixed css layout on event date/location

---

capacity4more/behat/features/bootstrap/FeatureContext/Group.php
capacity4more/behat/features/group_manage_categories.feature

CFD-384 Behat testing adding a term or category type.

---

capacity4more/modules/c4m/features_og/c4m_features_og_manage/plugins/content_types/group_details/group-details.tpl.php

CFD-498 Fatal error on manage group page

---

capacity4more/modules/c4m/content/c4m_content_document/c4m_content_document.module

https://issuetracker.amplexor.com/jira/browse/CFD-450

CFD-450 check box in document create full form should not be

---

capacity4more/modules/c4m/features/c4m_features_homepage/plugins/content_types/video_embed/video_embed.inc
capacity4more/themes/c4m/kapablo/sass/components/_homepage.scss

https://issuetracker.amplexor.com/jira/browse/CFD-475

CFD-475 video does not turn off when container is closed

---

capacity4more/themes/c4m/kapablo/sass/base/_fields.scss

CFD-315 - Activity stream overflow

---

capacity4more/modules/c4m/field/c4m_field_og/includes/c4m_field_og.theme.node.inc

Only show the group when it is available.

CFD-493 Fix warning

---

capacity4more/behat/features/group_discussions.feature
capacity4more/behat/features/group_documents.feature
capacity4more/behat/features/group_events.feature
capacity4more/capacity4more.info
capacity4more/modules/c4m/content/c4m_content_article/c4m_content_article.strongarm.inc
capacity4more/modules/c4m/content/c4m_content_banner/c4m_content_banner.strongarm.inc
capacity4more/modules/c4m/content/c4m_content_book/c4m_content_book.strongarm.inc
capacity4more/modules/c4m/content/c4m_content_discussion/c4m_content_discussion.strongarm.inc
capacity4more/modules/c4m/content/c4m_content_document/c4m_content_document.strongarm.inc
capacity4more/modules/c4m/content/c4m_content_event/c4m_content_event.strongarm.inc
capacity4more/modules/c4m/content/c4m_content_featured/c4m_content_featured.strongarm.inc
capacity4more/modules/c4m/content/c4m_content_inthe_picture/c4m_content_inthe_picture.strongarm.inc
capacity4more/modules/c4m/content/c4m_content_organisation/c4m_content_organisation.strongarm.inc
capacity4more/modules/c4m/content/c4m_content_page_element/c4m_content_page_element.strongarm.inc
capacity4more/modules/c4m/content/c4m_content_photo/c4m_content_photo.strongarm.inc
capacity4more/modules/c4m/content/c4m_content_photoalbum/c4m_content_photoalbum.strongarm.inc
capacity4more/modules/c4m/content/c4m_content_project/c4m_content_project.strongarm.inc
capacity4more/modules/c4m/content/c4m_content_region/c4m_content_region.strongarm.inc
capacity4more/modules/c4m/content/c4m_content_task/c4m_content_task.strongarm.inc
capacity4more/modules/c4m/content/c4m_content_tasklist/c4m_content_tasklist.strongarm.inc
capacity4more/modules/c4m/content/c4m_content_topic/c4m_content_topic.strongarm.inc
capacity4more/modules/c4m/content/c4m_content_wiki_page/c4m_content_wiki_page.strongarm.inc

Preview button is disabled on all content forms

CFD-452 disable content preview

---

capacity4more/modules/c4m/vocab/c4m_vocab_widget/c4m_vocab_widget.module

CFD-329 : formatting bug on vocabulary lists

---

capacity4more/modules/c4m/features/c4m_features_homepage/templates/voices-views-carousel.tpl.php
capacity4more/themes/c4m/kapablo/sass/components/_carousel.scss

https://issuetracker.amplexor.com/jira/browse/CFD-458
> We’ll have to add the link only on the title and make it visually clear it is a link.

CFD-458 : Make title as link on the carousel 

---

capacity4more/behat/features/homepage.feature
capacity4more/modules/c4m/content/c4m_content_featured/c4m_content_featured.features.field_instance.inc
capacity4more/modules/c4m/content/c4m_content_featured/c4m_content_featured.module
capacity4more/modules/c4m/content/c4m_content_featured/c4m_content_featured.strongarm.inc
capacity4more/modules/c4m/content/c4m_content_featured/plugins/content_types/featured_block/featured_block.inc
capacity4more/modules/c4m/field/c4m_field_media/c4m_field_media.features.inc
capacity4more/modules/c4m/field/c4m_field_media/c4m_field_media.info
capacity4more/themes/c4m/kapablo/sass/components/_homepage.scss

https://issuetracker.amplexor.com/jira/browse/CFD-478

CFD-478 : featured block is moving around the pictures in the container generating white space

---

capacity4more/modules/c4m/features/c4m_features_overview_events/c4m_features_overview_events.views_default.inc
capacity4more/modules/c4m/features_og/c4m_features_og_discussions/c4m_features_og_discussions.views_default.inc
capacity4more/modules/c4m/features_og/c4m_features_og_documents/c4m_features_og_documents.views_default.inc
capacity4more/modules/c4m/features_og/c4m_features_og_events/c4m_features_og_events.views_default.inc
capacity4more/modules/c4m/features_og/c4m_features_og_members/c4m_features_og_members.views_default.inc
capacity4more/modules/c4m/search/c4m_search/c4m_search.features.inc
capacity4more/modules/c4m/search/c4m_search_nodes/c4m_search_nodes.views_default.inc

Created a full text searchable field for first & lastname.
Renamed all the search input labels to "Search" (vs Fulltext Search, Browse etc).

CFD-446 search members by name

---

capacity4more/modules/c4m/domain/c4m_domain/c4m_domain.install
capacity4more/modules/c4m/domain/c4m_domain/c4m_domain.module

Added whitelist field with validation.
Added index on name.

CFD-524 Added whitelist field to email_domain.

---

capacity4more/capacity4more.profile
capacity4more/drupal-org.make

Patch applied in make file.
Variable set during install (profile).

CFD-465 - Menu navigation doesnt work from access denied

---

capacity4more/modules/c4m/search/c4m_search/c4m_search.facetapi_defaults.inc
capacity4more/modules/c4m/search/c4m_search/c4m_search.info
capacity4more/modules/c4m/search/c4m_search/c4m_search.module
capacity4more/modules/c4m/search/c4m_search/plugins/facetapi/widget_links_content_types.inc

CFD-530 Content type facet

---

capacity4more/capacity4more.info
capacity4more/modules/c4m/features/c4m_features_overview_articles/c4m_features_overview_articles.module
capacity4more/modules/c4m/features/c4m_features_overview_groups/c4m_features_overview_groups.module
capacity4more/modules/c4m/features/c4m_features_overview_people/c4m_features_overview_people.module
capacity4more/modules/c4m/features_og/c4m_features_og_search/c4m_features_og_search.context.inc
capacity4more/modules/c4m/features_og/c4m_features_og_search/c4m_features_og_search.features.inc
capacity4more/modules/c4m/features_og/c4m_features_og_search/c4m_features_og_search.info
capacity4more/modules/c4m/features_og/c4m_features_og_search/c4m_features_og_search.module
capacity4more/modules/c4m/features_og/c4m_features_og_search/c4m_features_og_search.views_default.inc
capacity4more/modules/c4m/og/c4m_og/c4m_og.module
capacity4more/modules/c4m/search/c4m_search/c4m_search.api.php
capacity4more/modules/c4m/search/c4m_search/c4m_search.module
capacity4more/modules/c4m/search/c4m_search/js/c4m_search.js
capacity4more/modules/c4m/search/c4m_search/plugins/facetapi/widget_links_content_types.inc
capacity4more/modules/c4m/search/c4m_search_nodes/c4m_search_nodes.module
capacity4more/themes/c4m/kapablo/sass/components/_search.scss
capacity4more/themes/c4m/kapablo/templates/page.tpl.php
capacity4more/themes/c4m/kapablo/theme/preprocess.inc

CFD-509 Group search

---

capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/controllers/drupalForm.js

https://issuetracker.amplexor.com/jira/browse/CFD-345
This fixes Diane's comment.
The function was not stopping in the right place.
The return was inside a ``forEach`` which just stopped the loop instead of stopping the function.
Fixed:

CFD-345 : topic selection is not limited to 3 topics

---

capacity4more/modules/c4m/features_og/c4m_features_og_manage/c4m_manage_categories.inc
capacity4more/themes/c4m/kapablo/sass/components/_taxonomy_form.scss

https://issuetracker.amplexor.com/jira/browse/CFD-531

CFD-531 Manage group categories: New group has no buttons to start adding categories

---

capacity4more/themes/c4m/kapablo/templates/node--document--library.tpl.php

https://issuetracker.amplexor.com/jira/browse/CFD-472
Permissions fixed in #660

CFD-472 : cannot upload document from the library to attach to another content

---

capacity4more/modules/c4m/features_og/c4m_features_og_manage/c4m_manage_categories.inc

https://issuetracker.amplexor.com/jira/browse/CFD-560

CFD-560 : Group Categories : Manage group categories errors

---

capacity4more/modules/c4m/content/c4m_content_group/c4m_content_group.features.field_base.inc
capacity4more/modules/c4m/content/c4m_content_group/c4m_content_group.features.field_instance.inc
capacity4more/modules/c4m/content/c4m_content_group/c4m_content_group.info
capacity4more/modules/c4m/og/c4m_og/plugins/entityreference/selection/C4MSelectionHandler.class.php
capacity4more/modules/c4m/og/c4m_og/plugins/entityreference/selection/c4m_selection.inc

https://issuetracker.amplexor.com/jira/browse/CFD-536

CFD-536 Search : Articles & projects are not group content.

---

capacity4more/capacity4more.profile
capacity4more/drupal-org.make

https://issuetracker.amplexor.com/jira/browse/CFD-472

CFD-472 : Update jQuery version.

---

capacity4more/modules/c4m/field/c4m_field_media/c4m_field_media.features.field_base.inc
capacity4more/modules/c4m/field/c4m_field_media/c4m_field_media.file_default_displays.inc
capacity4more/modules/c4m/widgets/c4m_document_widget/c4m_document_widget.module

https://issuetracker.amplexor.com/jira/browse/CFD-595

CFD-595 Document Library : Use smaller image preview when uploading an image as attachment to group content

---

capacity4more/capacity4more.install
capacity4more/drupal-org.make
capacity4more/modules/c4m/features_og/c4m_features_og_wiki/c4m_features_og_wiki.features.inc
capacity4more/modules/c4m/features_og/c4m_features_og_wiki/c4m_features_og_wiki.info
capacity4more/modules/c4m/features_og/c4m_features_og_wiki/c4m_features_og_wiki.install
capacity4more/modules/c4m/features_og/c4m_features_og_wiki/c4m_features_og_wiki.module
capacity4more/modules/c4m/features_og/c4m_features_og_wiki/c4m_features_og_wiki.views_default.inc

CFD-526 wiki rearrange book pages

---

capacity4more/behat/features/bootstrap/FeatureContext.php
capacity4more/behat/features/bootstrap/FeatureContext/GroupMembers.php
capacity4more/behat/features/bootstrap/FeatureContext/People.php
capacity4more/behat/features/group_members.feature
capacity4more/behat/features/people.feature
capacity4more/modules/c4m/user/c4m_user_profile/c4m_user_profile.module

+ Added tests for the people & Members overview pages.

Fix broken People & Members overview pages

---

capacity4more/modules/c4m/content/c4m_content_feed/c4m_content_feed.pages.inc

Unknown data property c4m_related_topic

Fixed EntityMetadataWrapperException

---

capacity4more/themes/c4m/kapablo/sass/components/_book_navigation.scss

Improve UX for WIKI page navigation

---

build/themes/kapablo/Gemfile
build/themes/kapablo/Gemfile.lock
build/themes/kapablo/Gruntfile.js
build/themes/kapablo/package.json
capacity4more/drupal-org-core.make
capacity4more/drupal-org.make
capacity4more/modules/c4m/content/c4m_content_photoalbum/c4m_content_photoalbum.install
capacity4more/modules/c4m/features/c4m_features_homepage_intro/js/video_overlay.js
capacity4more/modules/c4m/features_og/c4m_features_og_manage/c4m_features_og_manage.module
capacity4more/modules/c4m/features_og/c4m_features_og_wiki/c4m_features_og_wiki.module
capacity4more/modules/c4m/og/c4m_og/c4m_og.access.inc
capacity4more/modules/c4m/og/c4m_og/plugins/entityreference/selection/C4MOgSelectionHandler.class.php
capacity4more/modules/c4m/restful/c4m_restful_quick_post/c4m_restful_quick_post.module
capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/c4m-app.js
capacity4more/modules/c4m/user/c4m_user/c4m_user.module
capacity4more/modules/c4m/user/c4m_user/includes/c4m_user.theme.inc
capacity4more/modules/c4m/vocab/c4m_vocab_topic/c4m_vocab_topic.install
capacity4more/modules/c4m/widgets/c4m_document_widget/c4m_document_widget.module

All fields that are used in a schema's key must have a "not null" => TRUE definition, otherwise MySQL will complain and installation will fail.
Drupal core update included.

Fix make script with mysql 5.7

---

project/profiles/capacity4more/modules/c4m/og/c4m_og/c4m_og.module

https://issuetracker.amplexor.com/jira/browse/CFM-604

Changing all pending members to be active when group access level is changed to open.

---

project/profiles/capacity4more/modules/c4m/features_og/c4m_features_og_manage/c4m_features_og_manage.module
project/profiles/capacity4more/modules/c4m/features_og/c4m_features_og_manage/plugins/content_types/group_details/group-details.tpl.php
project/profiles/capacity4more/modules/c4m/og/c4m_og/c4m_og.module

https://issuetracker.amplexor.com/jira/browse/CFM-1038

[CFM-1038] Adding a form to replace a group owner.

---

project/profiles/capacity4more/modules/c4m/og/c4m_og/c4m_og.module

https://issuetracker.amplexor.com/jira/browse/CFM-1040

[CFM-1040] Delete all pending memberships when a group go private.

---

project/profiles/capacity4more/modules/c4m/message/c4m_message/c4m_message.module

No need to wrap the body with template - done by mimemail module.

Notify user on membership activation with Email rework

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_profile/c4m_user_profile.module

https://issuetracker.amplexor.com/jira/browse/CFM-1187

[CFM-1187] Deny access to the c4m_unsubscribe_hash field.

---

project/profiles/capacity4more/modules/c4m/domain/c4m_domain/c4m_domain.module

https://issuetracker.amplexor.com/jira/browse/CFM-1323

[CFM-1323] Allow access for admins only to the Email entity.

---

project/profiles/capacity4more/modules/c4m/admin/c4m_admin_organisations/c4m_admin_organisations.views_default.inc

https://issuetracker.amplexor.com/jira/browse/CFM-1320

[CFM-1320] Remove the link to the organization.

---

project/profiles/capacity4more/modules/c4m/content/c4m_content_group/c4m_content_group.block.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_topic/c4m_content_topic.path_breadcrumbs.inc
project/profiles/capacity4more/modules/c4m/og/c4m_og_purl/c4m_og_purl.module

https://issuetracker.amplexor.com/jira/browse/CFM-1467

[BUGFIX] Maximum nesting level of 256 (admin pages).

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_admin/c4m_user_admin.strongarm.inc

With Kevins' approval.
https://issuetracker.amplexor.com/jira/browse/CFM-1423

[CFM-1423] Disable user blocked email notification.

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_notifications/c4m_user_notifications.module
project/profiles/capacity4more/modules/c4m/user/c4m_user_notifications/includes/c4m_user_notifications_handlers.inc

New function created = > used both for  open and moderated groups wellcome notification.
https://issuetracker.amplexor.com/jira/browse/CFM-1414

[CFM-1414-fix] Fix the wellcome to group email notification

---

project/profiles/capacity4more/modules/c4m/features_og/c4m_features_og_group_dashboard/c4m_features_og_group_dashboard.features.inc
project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/base/_global.scss

https://issuetracker.amplexor.com/jira/browse/CFM-1183

[CFM-1183] Changing the recommended flag.

---

project/profiles/capacity4more/modules/c4m/content/c4m_content_group/c4m_content_group.module

@soniCaH 
Please merge this asap since it cause FATAL Errors ...
thanks

Fixing issues on the c4m_content_group.module file.

---

project/profiles/capacity4more/modules/c4m/content/c4m_content_group/templates/c4m_og_vocab.tpl.php

@soniCaH 
I'm merging this one since it cause the other branches to fail ...

Fixing the sniffer.

---

project/profiles/capacity4more/modules/c4m/features/c4m_features_homepage/c4m_features_homepage.module

https://issuetracker.amplexor.com/jira/browse/CFM-1466

[CFM-1466] Activity Stream groups filter

---

project/profiles/capacity4more/modules/c4m/features/c4m_features_homepage_intro/js/video_overlay.js
project/profiles/capacity4more/modules/c4m/features/c4m_features_homepage_intro/templates/video-overlay.tpl.php
project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/components/_homepage.scss

https://issuetracker.amplexor.com/jira/browse/CFM-1054

[CFM-1054] Adding a close button for the youtube video on the homepage.

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_og/c4m_user_og.module
project/profiles/capacity4more/modules/c4m/user/c4m_user_og/c4m_user_og.page.inc

https://issuetracker.amplexor.com/jira/browse/CFM-1481
@janlemmens 
This one is dependent on #1044

[CFM-1481] Display the buttons also for logged in users.

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_og/c4m_user_og.install
project/profiles/capacity4more/modules/c4m/user/c4m_user_og/c4m_user_og.module

https://issuetracker.amplexor.com/jira/browse/CFM-908

[CFM-908] Store gid+uid of a user after registration.

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_og/c4m_user_og.module

https://issuetracker.amplexor.com/jira/browse/CFM-911

[CFM-911] Associate user to group after login/activation.

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_og/c4m_user_og.module
project/profiles/capacity4more/modules/c4m/user/c4m_user_og/c4m_user_og.page.inc

https://issuetracker.amplexor.com/jira/browse/CFM-909

[CFM-909] Redirect user to the group after activation.

---

project/profiles/capacity4more/modules/c4m/features/c4m_features_theme/c4m_features_theme.module
project/profiles/capacity4more/modules/c4m/user/c4m_user_og/c4m_user_og.install
project/profiles/capacity4more/modules/c4m/user/c4m_user_og/c4m_user_og.module
project/profiles/capacity4more/modules/c4m/user/c4m_user_og/c4m_user_og.page.inc
project/profiles/capacity4more/modules/c4m/user/c4m_user_og/messages/user_registrationpassword_register_to_group_body.html
project/profiles/capacity4more/modules/c4m/user/c4m_user_og/templates/c4m_unified_workflow_login.tpl.php
project/profiles/capacity4more/modules/c4m/user/c4m_user_og/templates/c4m_unified_workflow_register.tpl.php
project/profiles/capacity4more/modules/c4m/user/c4m_user_profile/c4m_user_profile.module

https://issuetracker.amplexor.com/jira/browse/CFM-903

[CFM-903] Unified registration/login + join/request.

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_og/c4m_user_og.module

https://issuetracker.amplexor.com/jira/browse/CFM-907

[CFM-907] Put the message body inside an array.

---

project/profiles/capacity4more/modules/c4m/content/c4m_content_photo/c4m_content_photo.module

https://issuetracker.amplexor.com/jira/browse/CFM-1211

[CFM-1211] Set the uploaded photos filenames by the album.

---

apache/config/includes/drupal-files-htaccess
apache/config/includes/drupal-private-files-htaccess
apache/config/includes/drupal-root-htaccess
apache/config/vhost-example.conf

https://issuetracker.amplexor.com/jira/browse/CFM-1357

CFM-1357: Apache config & example vhost

---

project/profiles/capacity4more/modules/c4m/features_og/c4m_features_og_group_dashboard/c4m_features_og_group_dashboard.module
project/profiles/capacity4more/modules/c4m/user/c4m_user_og/c4m_user_og.module

Each implementation on the hook can provide complex themes and provide a weight for the items added to the CTA block.
Jira issue: https://issuetracker.amplexor.com/jira/browse/CFM-1205

CFM-1205: Replaces custom alter hook with a hook that uses render arrays

---

project/profiles/capacity4more/behat/features/group_discussions.feature
project/profiles/capacity4more/modules/c4m/content/c4m_content/c4m_content.module

Since we are using our own states, we don't need the contrib 'Unpublish' button.
**Before:**
**After:**
**JIRA:** https://issuetracker.amplexor.com/jira/browse/CFM-1244

[Feature/CFM-1244] Remove 'Unpublish' button from forms

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_profile/c4m_user_profile.module
project/profiles/capacity4more/modules/c4m/user/c4m_user_profile/c4m_user_profile.pages.inc

Adds a page where the user can leave the platform.
Issue: https://issuetracker.amplexor.com/jira/browse/CFM-787
In the next picture can be seen the leave link (on the tabs, as also appears on the user profile), and the form to leave the platform.

CFM-787: Create custom "leave" page

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_og/c4m_user_og.module

Issue: https://issuetracker.amplexor.com/jira/browse/CFM-922

CFM-922: Adds a message when a user is already a member of the group

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_admin/actions/c4m_user_admin.action.inc
project/profiles/capacity4more/modules/c4m/user/c4m_user_admin/c4m_user_admin.info
project/profiles/capacity4more/modules/c4m/user/c4m_user_admin/c4m_user_admin.module
project/profiles/capacity4more/modules/c4m/user/c4m_user_admin/c4m_user_admin.pages.inc
project/profiles/capacity4more/modules/c4m/user/c4m_user_admin/c4m_user_admin.views_default.inc
project/profiles/capacity4more/modules/c4m/user/c4m_user_admin/include/views_handler_field_user_link_activate.inc
project/profiles/capacity4more/modules/c4m/user/c4m_user_admin/include/views_handler_field_user_link_reactivate.inc
project/profiles/capacity4more/modules/c4m/user/c4m_user_admin/include/views_handler_field_user_link_resend_activation_email.inc

https://issuetracker.amplexor.com/jira/browse/CFM-1313

[CFM-1313] Reactivate user link + notification.

---

project/profiles/capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/controllers/activity.js

https://issuetracker.amplexor.com/jira/browse/CFM-1380

[CFM-1380] -Bootstrap's tooltip JS in activity stream messages.

---

project/profiles/capacity4more/modules/c4m/content/c4m_content_event/c4m_content_event.ds.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_event/c4m_content_event.features.field_instance.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_event/c4m_content_event.strongarm.inc
project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/components/_events.scss
project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/states/_teaser.scss

https://issuetracker.amplexor.com/jira/browse/CFM-1067
Wireframe:

[CFM-1067] Event Teaser View theming

---

project/profiles/capacity4more/modules/c4m/features/c4m_features_homepage/c4m_features_homepage.features.inc
project/profiles/capacity4more/modules/c4m/features/c4m_features_homepage/c4m_features_homepage.module
project/profiles/capacity4more/modules/c4m/features/c4m_features_homepage/c4m_features_homepage.pages_default.inc

Adds the CTA block to the homepage and adds an action to add a button to create a group.
Issue: https://issuetracker.amplexor.com/jira/browse/CFM-1239

CFM-1239: Create CTA buttons to initiate new group creation

---

project/profiles/capacity4more/modules/c4m/features_og/c4m_features_og_discussions/c4m_features_og_discussions.views_default.inc
project/profiles/capacity4more/modules/c4m/views/c4m_views/views/handlers/c4m_views_handler_area_node_add.inc
project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/components/_blocks.scss

https://issuetracker.amplexor.com/jira/browse/CFM-1410
The implementation would be through the UI, in contrast of the previous PRs which took care of it through hard-coding.

[CFM-1410] "New Discussion" button - permissions & styling

---

project/profiles/capacity4more/modules/c4m/content/c4m_content_group/c4m_content_group.module

Issue: https://issuetracker.amplexor.com/jira/browse/CFM-1238

CFM-1238 Implement group status flow

---

project/profiles/capacity4more/modules/c4m/features_og/c4m_features_og_discussions/c4m_features_og_discussions.views_default.inc
project/profiles/capacity4more/modules/c4m/features_og/c4m_features_og_documents/c4m_features_og_documents.views_default.inc
project/profiles/capacity4more/modules/c4m/views/c4m_views/views/handlers/c4m_views_handler_area_node_add.inc
project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/components/_blocks.scss

Merging to #1074, where the implementation occurs.
JIRA: https://issuetracker.amplexor.com/jira/browse/CFM-1412

[CFM-1412] "Upload Document" button - permissions & styling

---

project/profiles/capacity4more/modules/c4m/message/c4m_message/plugins/content_types/activity_stream/activity-stream.tpl.php
project/profiles/capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/controllers/activity.js
project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/components/_homepage.scss

https://issuetracker.amplexor.com/jira/browse/CFM-1475

[CFM-1475] Show spinner when loading more messages 

---

.travis.yml

@soniCaH 
Feel free to revert this one if/when needed

Run travis for all branches.

---

project/profiles/capacity4more/modules/c4m/search/c4m_search/c4m_search.module

[CFM-1464](https://issuetracker.amplexor.com/jira/browse/CFM-1464)

CFM-1464: Preserve sorting.

---

project/profiles/capacity4more/modules/c4m/content/c4m_content_photo/c4m_content_photo.module
project/profiles/capacity4more/modules/c4m/content/c4m_content_photo/theme/node-gallery-api-item-navigator.tpl.php

https://issuetracker.amplexor.com/jira/browse/CFM-1388
@soniCaH 
This one if fixing #949

[CFM-1388] Disabling the purl on links produced by the node

---

project/profiles/capacity4more/behat/features/unified_workflow.feature
project/profiles/capacity4more/modules/c4m/user/c4m_user_og/c4m_user_og.module

https://issuetracker.amplexor.com/jira/browse/CFM-910

[CFM-910] Fixing unified workflow + adding a test

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_profile/c4m_user_profile.module

Moves the link to leave the platform to the actions of the edit profile form.
Issue: https://issuetracker.amplexor.com/jira/browse/CFM-785
Screenshot:

CFM-785: Add "leave platform" link to user profile

---

project/profiles/capacity4more/modules/c4m/features/c4m_features_homepage_intro/js/video_overlay.js

https://issuetracker.amplexor.com/jira/browse/CFM-1054

[CFM-1054] Fix banner video at IE9 and 10

---

project/profiles/capacity4more/modules/c4m/restful/c4m_restful_quick_post/c4m_restful_quick_post.module

https://issuetracker.amplexor.com/jira/browse/CFM-208

[CFM-208] Fixing the access callback of the quick-post.

---

project/profiles/capacity4more/modules/c4m/content/c4m_content/includes/c4m_content.theme.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_photo/c4m_content_photo.module

[CFM-1136](https://issuetracker.amplexor.com/jira/browse/CFM-1136)

CFM-1136: Media statistics

---

project/profiles/capacity4more/modules/c4m/og/c4m_og_purl/c4m_og_purl.module

https://issuetracker.amplexor.com/jira/browse/CFM-1467

[CFM-1467] Fixing the Maximum nesting level error.

---

project/profiles/capacity4more/modules/c4m/restful/c4m_restful_quick_post/c4m_restful_quick_post.module
project/profiles/capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/controllers/main.js
project/profiles/capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/services/request.js
project/profiles/capacity4more/modules/c4m/restful/c4m_restful_quick_post/templates/quick-post-form.tpl.php

https://issuetracker.amplexor.com/jira/browse/CFM-932

[CFM-932] Removing the events and documents from the quickpost.

---

project/profiles/capacity4more/modules/c4m/content/c4m_content_article/c4m_content_article.strongarm.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_banner/c4m_content_banner.strongarm.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_book/c4m_content_book.strongarm.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_featured/c4m_content_featured.strongarm.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_feed/c4m_content_feed.strongarm.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_group/c4m_content_group.strongarm.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_inthe_picture/c4m_content_inthe_picture.strongarm.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_project/c4m_content_project.strongarm.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_share/c4m_content_share.strongarm.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_topic/c4m_content_topic.strongarm.inc
project/profiles/capacity4more/modules/c4m/demo/c4m_demo_fields/c4m_demo_fields.strongarm.inc

https://issuetracker.amplexor.com/jira/browse/CFM-942

[CFM-942] Removing preview option from comments.

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_profile/c4m_user_profile.module
project/profiles/capacity4more/modules/c4m/user/c4m_user_profile/c4m_user_profile.pages.inc

Fixes errors on the user cancellation form submit callback.
Previous PR: https://github.com/capacity4dev/capacity4more/pull/1096
Issue: https://issuetracker.amplexor.com/jira/browse/CFM-789

[CFM-789] Confirm handler of the "leave platform" page

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_profile/c4m_user_profile.module

Hides deletion fields from the user edit form.
Issue: https://issuetracker.amplexor.com/jira/browse/CFM-794

[CFM-794] Hide user deletion fields from edit user form

---

project/profiles/capacity4more/modules/c4m/features/c4m_features_homepage/plugins/content_types/my_groups/my-groups.tpl.php
project/profiles/capacity4more/modules/c4m/features/c4m_features_homepage/plugins/content_types/my_groups/my_groups.inc

Refactorizes the way the user groups are loaded to meet the requested specification.
Issue: https://issuetracker.amplexor.com/jira/browse/CFM-443
No screenshot, just code changes.

CFM-443: Create function to retrieve all user groups grouped by membership

---

project/profiles/capacity4more/modules/c4m/features/c4m_features_homepage/c4m_features_homepage.module

Replaces link that filters by each user topic with single filter.
Issue: https://issuetracker.amplexor.com/jira/browse/CFM-1192
Previous PR: https://github.com/capacity4dev/capacity4more/pull/1116

CFM-1192: Create view block to display suggested groups

---

project/profiles/capacity4more/modules/c4m/og/c4m_og/c4m_og.access.inc

https://issuetracker.amplexor.com/jira/browse/CFM-890

[CFM-888] Only SA can delete group/project

---

project/profiles/capacity4more/modules/c4m/user/c4m_user/c4m_user.module

https://issuetracker.amplexor.com/jira/browse/CFM-1260

[CFM-1260] Removing the header.

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_og/c4m_user_og.module

[BUGFIX] Remove duplication of cta block for visitors. [ci skip]

---

.travis.yml

@soniCaH 
Created this one since we already need that in more than 1 PR.

Install drupal on travis under the installation section.

---

project/profiles/capacity4more/modules/c4m/content/c4m_content_share/c4m_content_share.ds.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_share/c4m_content_share.features.field_instance.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_share/c4m_content_share.module
project/profiles/capacity4more/modules/c4m/content/c4m_content_share/includes/c4m_content_share.theme.inc
project/profiles/capacity4more/modules/c4m/og/c4m_og/c4m_og.module
project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/components/_share.scss
project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/kapablo.scss

[CFM-506](https://issuetracker.amplexor.com/jira/browse/CFM-506)

CFM-506: share content between groups

---

project/profiles/capacity4more/modules/c4m/content/c4m_content/includes/c4m_content.theme.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_photo/c4m_content_photo.module
project/profiles/capacity4more/modules/c4m/content/c4m_content_photoalbum/c4m_content_photoalbum.module
project/profiles/capacity4more/modules/c4m/features_og/c4m_features_og_manage/js/manage_features.js
project/profiles/capacity4more/modules/c4m/features_og/c4m_features_og_media/c4m_features_og_media.install
project/profiles/capacity4more/modules/c4m/features_og/c4m_features_og_media/c4m_features_og_media.views_default.inc
project/profiles/capacity4more/modules/c4m/og/c4m_og/c4m_og.module

https://issuetracker.amplexor.com/jira/browse/CFM-1213

[CFM-1213] -Manage Group Media Feature

---

config/make/views.make

Bug reported on vbo 3.2, and wasn't fixed at 3.3: https://www.drupal.org/node/2334625
https://issuetracker.amplexor.com/jira/browse/CFM-311

[CFM-311-fix]  fix vbo functionality when 'select all pages'  is selected on last page

---

project/profiles/capacity4more/modules/c4m/content/c4m_content/c4m_content.module

https://issuetracker.amplexor.com/jira/browse/CFM-1225

[CFM-1225-fix] Update confirmation message text

---

project/profiles/capacity4more/modules/c4m/search/c4m_search_og/c4m_search_og.module
project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/components/_search.scss

https://issuetracker.amplexor.com/jira/browse/CFM-1274

[CFM-1274] -search form is no longer in the group menu.

---

project/profiles/capacity4more/modules/c4m/content/c4m_content_group/c4m_content_group.block.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_group/theme/c4m-content-group-header-title.tpl.php
project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/components/_groups.scss

[CFM-1514](https://issuetracker.amplexor.com/jira/browse/CFM-1514)

CFM-1514: Restricted details theming fixes

---

project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/base/_global.scss
project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/components/_navigation.scss

[CFM-1515](https://issuetracker.amplexor.com/jira/browse/CFM-1515)

CFM-1515: offcanvas styling bugs

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_og/c4m_user_og.module

[CFM-607](https://issuetracker.amplexor.com/jira/browse/CFM-607)

CFM-607: Help & guidance link always visible

---

project/profiles/capacity4more/modules/c4m/user/c4m_user/c4m_user.module
project/profiles/capacity4more/modules/c4m/user/c4m_user_notifications/c4m_user_notifications.module
project/profiles/capacity4more/modules/c4m/user/c4m_user_notifications/includes/c4m_user_notifications_handlers.inc

[CFM-1292](https://issuetracker.amplexor.com/jira/browse/CFM-1292)

[CFM-1292] -Extend OG functionality to add users.

---

project/profiles/capacity4more/modules/c4m/message/c4m_message/c4m_message.module

https://issuetracker.amplexor.com/jira/browse/CFM-966

[CFM-966] Setting the threshold timing for integrating messages.

---

project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/base/_global.scss
project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/components/_navigation.scss

[CFM-1515](https://issuetracker.amplexor.com/jira/browse/CFM-1515)

CFM-1515: Offcanvas fix

---

project/profiles/capacity4more/modules/c4m/admin/c4m_admin_groups/c4m_admin_groups.views_default.inc

@soniCaH 
I'm not sure if there is a ticket relating to this one, but I've just found it, so, why not :)

Fixing pending groups view. [ci skip]

---

project/profiles/capacity4more/modules/c4m/message/c4m_message/c4m_message.module

https://issuetracker.amplexor.com/jira/browse/CFM-1456

[CFM-1456] Disable message creation when adding images to a photoalbum

---

project/profiles/capacity4more/modules/c4m/features_og/c4m_features_og_wiki/c4m_features_og_wiki.module
project/profiles/capacity4more/modules/c4m/features_og/c4m_features_og_wiki/c4m_features_og_wiki.views_default.inc

[CFM-191](https://issuetracker.amplexor.com/jira/browse/CFM-191)

[CFM-191] -Unpublished pages do not appear under rearrange pages.

---

project/profiles/capacity4more/modules/c4m/message/c4m_message/c4m_message.module

Solves an issue on c4m_message that was causing an error when creating a new user.

[BUG] When creating a new user programmatically, c4m_messages crashes

---

project/profiles/capacity4more/modules/c4m/features/c4m_features_social/c4m_features_social.module
project/profiles/capacity4more/modules/c4m/features/c4m_features_social/theme/c4m-features-social-actions-share.tpl.php

Filters the social links to restrict them depending on the group membership type.
Issue: https://issuetracker.amplexor.com/jira/browse/CFM-1181

[CFM-1181] Limits social links depending on group membership type

---

project/profiles/capacity4more/modules/c4m/features/c4m_features_homepage/c4m_features_homepage.pages_default.inc
project/profiles/capacity4more/modules/c4m/features/c4m_features_social/c4m_features_social.module

Issue: https://issuetracker.amplexor.com/jira/browse/CFM-1180

[CFM-1180] Add social sharing block to specific pages

---

project/profiles/capacity4more/behat/features/bootstrap/FeatureContext/QuickPost.php
project/profiles/capacity4more/behat/features/quick_post.feature
project/profiles/capacity4more/modules/c4m/restful/c4m_restful_quick_post/templates/quick-post-form.tpl.php
project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/components/_quickpost.scss

https://issuetracker.amplexor.com/jira/browse/CFM-1224
* Hidden on mobile

[CFM-1224] Adding the notifications checkbox on the quickpost form.

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_og/c4m_user_og.module

[BUGFIX] Fixing an error on the project homepage.

---

project/profiles/capacity4more/modules/c4m/vocab/c4m_vocab_topic/c4m_vocab_topic.module

[CFM-181](https://issuetracker.amplexor.com/jira/browse/CFM-181)

CFM-181: Topic vocab mapping by destination

---

project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/base/_settings.scss
project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/components/_forms.scss
project/profiles/capacity4more/themes/c4m/kapablo/templates/dnd-upload-droppable-area.tpl.php
project/profiles/capacity4more/themes/c4m/kapablo/theme/forms.inc

https://issuetracker.amplexor.com/jira/browse/CFM-1208

[CFM-1208] Theming the c4m_document field widget.

---

project/profiles/capacity4more/modules/c4m/content/c4m_content_featured/c4m_content_featured.features.field_instance.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_featured/c4m_content_featured.module

[CFM-1518](https://issuetracker.amplexor.com/jira/browse/CFM-1518)

CFM-1518: Title & body limit

---

project/profiles/capacity4more/modules/c4m/content/c4m_content_article/c4m_content_article.module

Fixing errors from article node view alter.

---

project/profiles/capacity4more/modules/c4m/content/c4m_content_share/c4m_content_share.module
project/profiles/capacity4more/modules/c4m/og/c4m_og/c4m_og.module

Fix for https://github.com/capacity4dev/capacity4more/commit/a4f914b0aa8c7ec45ab3b3d1c581ffa4a84669bd#commitcomment-18892965
Please review if this is the proper use for registering.

CFM-560 - Extract og_context_access_callback_register to access callback.

---

project/profiles/capacity4more/modules/c4m/features_og/c4m_features_og_members/c4m_features_og_members.module
project/profiles/capacity4more/modules/c4m/message/c4m_message/c4m_message.module

https://issuetracker.amplexor.com/jira/browse/CFM-1257

[BUGFIX] determine power user.

---

project/profiles/capacity4more/modules/c4m/og/c4m_og_purl/c4m_og_purl.module
project/profiles/capacity4more/modules/c4m/user/c4m_user/c4m_user.module
project/profiles/capacity4more/modules/c4m/user/c4m_user_bar/c4m_user_bar.block.inc
project/profiles/capacity4more/modules/c4m/user/c4m_user_profile/c4m_user_profile.block.inc

[CFM-1508](https://issuetracker.amplexor.com/jira/browse/CFM-1508)

CFM-1508: Login & logout link which are og_context aware

---

project/profiles/capacity4more/behat/features/bootstrap/FeatureContext/File.php
project/profiles/capacity4more/behat/features/files_upload.feature
project/profiles/capacity4more/capacity4more.install
project/profiles/capacity4more/capacity4more.profile

https://issuetracker.amplexor.com/jira/browse/CFM-1506

[CFM-1506] Testing the file upload form.

---

project/profiles/capacity4more/modules/c4m/og/c4m_og_purl/c4m_og_purl.module

[BUGFIX] group content link with no access led to that.

---

apache/config/includes/drupal-private-files-htaccess
apache/config/includes/drupal-root-htaccess
apache/config/vhost-example.conf
config/make/_core.make

[CFM-1357](https://issuetracker.amplexor.com/jira/browse/CFM-1357)

CFM-1357: Apache config update according to DIGIT's proposal

---

project/profiles/capacity4more/modules/c4m/message/c4m_message/c4m_message.module

https://issuetracker.amplexor.com/jira/browse/CFM-843

[CFM-843] Fix: Add anchor to group edit status link

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_og/c4m_user_og.module
project/profiles/capacity4more/modules/c4m/user/c4m_user_og/messages/user_registrationpassword_register_to_group_body.html

https://issuetracker.amplexor.com/jira/browse/CFM-1036

[CFM-1036] Fix Activation mail, per MT18 requirements

---

project/profiles/capacity4more/modules/c4m/message/c4m_message/c4m_message.module
project/profiles/capacity4more/modules/c4m/user/c4m_user_notifications/c4m_user_notifications.module

https://issuetracker.amplexor.com/jira/browse/CFM-834

[CFM-834] Fixes: Resolve label of organisation type, don't notify admins on member invitation & when invitation is accepted.

---

project/profiles/capacity4more/modules/c4m/content/c4m_content_share/c4m_content_share.pages.inc

[CFM-1234](https://issuetracker.amplexor.com/jira/browse/CFM-1234)

CFM-1234: Shared wiki pages should not appear in menu of group

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_profile/c4m_user_profile.module

[CFM-800](https://issuetracker.amplexor.com/jira/browse/CFM-800)

CFM-800: Correct order of user login form validation

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_admin/c4m_user_admin.views_default.inc

[CFM-1325](https://issuetracker.amplexor.com/jira/browse/CFM-1325)

CFM-1325: Users export - vertical separator

---

project/profiles/capacity4more/modules/c4m/og/c4m_og/c4m_og.module
project/profiles/capacity4more/modules/c4m/user/c4m_user_notifications/c4m_user_notifications.module
project/profiles/capacity4more/modules/c4m/user/c4m_user_subscribe/c4m_user_subscribe.module

https://issuetracker.amplexor.com/jira/browse/CFM-558

[CFM-558] Fix: Add 'news' to group content notification types, and also 'article' for comments.

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_admin/c4m_user_admin.module
project/profiles/capacity4more/modules/c4m/user/c4m_user_admin/c4m_user_admin.pages.inc

https://issuetracker.amplexor.com/jira/browse/CFM-1313

[CFM-1313] Fix: On user reactivation, send welcome message if checkbox is checked

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_og/c4m_user_og.module

Issue: https://issuetracker.amplexor.com/jira/browse/CFM-875
Logged in as Galileo, who is Group Admin of Nobelprize (on the URL).
GA succesfully demoted, appears as member and the cogwheel doesn't appear anymore.

[CFM-875] GA can demote himself from group

---

project/profiles/capacity4more/behat/features/group_dashboard.feature
project/profiles/capacity4more/modules/c4m/og/c4m_og_invite_users/c4m_og_invite_users.module

https://issuetracker.amplexor.com/jira/browse/CFM-1043

[CFM-1043] Adding a link to the group memberships on the invite users.

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_notifications/c4m_user_notifications.module

https://issuetracker.amplexor.com/jira/browse/CFM-1538

[CFM-1538] Cancel notification when content is linked to anonymous user

---

project/profiles/capacity4more/modules/c4m/content/c4m_content_project/c4m_content_project.module

https://issuetracker.amplexor.com/jira/browse/CFM-1359
https://issuetracker.amplexor.com/jira/browse/CFM-1348

[CFM-1359] Follow / unfollow project

---

project/profiles/capacity4more/modules/c4m/message/c4m_message/c4m_message.module
project/profiles/capacity4more/themes/c4m/kapablo/theme/preprocess.inc

https://issuetracker.amplexor.com/jira/browse/CFM-1213

[CFM-1213] Fixing markup + creation of a photo message

---

project/profiles/capacity4more/modules/c4m/helper/c4m_helper_entity/c4m_helper_entity.module

[CFM-1539](https://issuetracker.amplexor.com/jira/browse/CFM-1539)

CFM-1539: Fixing group comment statistics query

---

project/profiles/capacity4more/modules/c4m/restful/c4m_restful_quick_post/c4m_restful_quick_post.module

https://issuetracker.amplexor.com/jira/browse/CFM-1480

[CFM-1480] Changing the path of the angular-app.

---

project/profiles/capacity4more/modules/c4m/og/c4m_og/c4m_og.module

https://issuetracker.amplexor.com/jira/browse/CFM-1292

[CFM-1292] Allow access to SA only for adding new members.

---

project/profiles/capacity4more/modules/c4m/og/c4m_og_invite_users/c4m_og_invite_users.module

[CFM-543](https://issuetracker.amplexor.com/jira/browse/CFM-543)

[CFM-543] Auto log-in invited users.

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_admin/c4m_user_admin.views_default.inc

[CFM-1325](https://issuetracker.amplexor.com/jira/browse/CFM-1325)

CFM-1325: User export fixes

---

project/profiles/capacity4more/modules/c4m/content/c4m_content_organisation/c4m_content_organisation.module
project/profiles/capacity4more/modules/c4m/user/c4m_user_profile/c4m_user_profile.api.php
project/profiles/capacity4more/modules/c4m/user/c4m_user_profile/c4m_user_profile.module

[CFM-1534](https://issuetracker.amplexor.com/jira/browse/CFM-1534)

CFM-1534: organisations validation

---

project/profiles/capacity4more/capacity4more.profile

[CFM-1233](https://issuetracker.amplexor.com/jira/browse/CFM-1233) & [CFM-1236](https://issuetracker.amplexor.com/jira/browse/CFM-1236)

CFM-1233: share og permissions

---

config/make/og.make

https://issuetracker.amplexor.com/jira/browse/CFM-1412

[CFM-1412] patch og module to use og_context_access_callback

---

project/profiles/capacity4more/modules/c4m/og/c4m_og/c4m_og.module

https://issuetracker.amplexor.com/jira/browse/CFM-1509

[CFM-1509] Grant access to group content by the same access of the group.

---

project/profiles/capacity4more/modules/c4m/comment/c4m_comment/c4m_comment.module
project/profiles/capacity4more/modules/c4m/features_og/c4m_features_og_group_dashboard/c4m_features_og_group_dashboard.module
project/profiles/capacity4more/modules/c4m/user/c4m_user_profile/c4m_user_profile.module
project/profiles/capacity4more/modules/c4m/user/c4m_user_profile/c4m_user_profile.pages.inc

https://issuetracker.amplexor.com/jira/browse/CFM-789

[CFM-789] Fixing the cancel account flow when anonymize content is selected.

---

project/profiles/capacity4more/modules/c4m/features_og/c4m_features_og_manage/c4m_features_og_manage.module

https://issuetracker.amplexor.com/jira/browse/CFM-1274

[CFM-1274] Changing the link from the project management to the menu navigation edit

---

project/profiles/capacity4more/modules/c4m/restful/c4m_restful/plugins/restful/node/activity_stream/1.0/C4mRestfulActivityStreamResource.class.php

https://issuetracker.amplexor.com/jira/browse/CFM-1197

[CFM-1197] Filter entities by related topics.

---

project/profiles/capacity4more/modules/c4m/og/c4m_og/plugins/entityreference/selection/C4MOgSelectionHandler.class.php

https://issuetracker.amplexor.com/jira/browse/CFM-1047

[CFM-1047] Fixing the access for power users when using the autocomplete on related projects.

---

project/profiles/capacity4more/modules/c4m/og/c4m_og_purl/c4m_og_purl.uri_info.inc

https://issuetracker.amplexor.com/jira/browse/CFM-929

[CFM-929] Fixing links formatted by purl link dashboard.

---

project/profiles/capacity4more/modules/c4m/message/c4m_message/c4m_message.module

https://issuetracker.amplexor.com/jira/browse/CFM-966

[CFM-966] Fixing the flow when checking the notifications ON.

---

project/profiles/capacity4more/modules/c4m/content/c4m_content_photo/c4m_content_photo.module
project/profiles/capacity4more/modules/c4m/features/c4m_features_theme/c4m_features_theme.module
project/profiles/capacity4more/modules/c4m/message/c4m_message/c4m_message.module

https://issuetracker.amplexor.com/jira/browse/CFM-1456

[CFM-1456] Adding a function to determine whether a photo is part of a photo album creation

---

project/profiles/capacity4more/modules/c4m/content/c4m_content/c4m_content.module

https://issuetracker.amplexor.com/jira/browse/CFM-1388

[CFM-1388] [BUGFIX] Access issue when using ajax requests within a new node form.

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_subscribe/c4m_user_subscribe.module

https://issuetracker.amplexor.com/jira/browse/CFM-960
https://issuetracker.amplexor.com/jira/browse/CFM-961

[CFM-961-fix] notification on article recomendation 

---

project/profiles/capacity4more/modules/c4m/content/c4m_content/c4m_content.module

https://issuetracker.amplexor.com/jira/browse/CFM-219

[CFM-219] Disable form validation when SA delete a node.

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_og/c4m_user_og.module

https://issuetracker.amplexor.com/jira/browse/CFM-970

[CFM-970] Adding weight to the follow group cta link.

---

project/profiles/capacity4more/modules/c4m/message/c4m_message/c4m_message.module

https://issuetracker.amplexor.com/jira/browse/CFM-961 - article teaser
https://issuetracker.amplexor.com/jira/browse/CFM-1187 - unsubscribe url

[CFM-961-fix] notification tokens

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_notifications/c4m_user_notifications.module

https://issuetracker.amplexor.com/jira/browse/CFM-965

[CFM-965-fix] Don't send notification when notification checkbox is not checked

---

project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/components/_book.scss

https://issuetracker.amplexor.com/jira/browse/CFM-1189

[CFM-1189] Fixing the help and guidance styling.

---

project/profiles/capacity4more/modules/c4m/features/c4m_contact/c4m_contact.module

https://issuetracker.amplexor.com/jira/browse/CFM-1178

[CFM-1178] Allow visitors to send a copy on the global contact form.

---

project/profiles/capacity4more/modules/c4m/restful/c4m_restful/plugins/restful/node/documents/1.0/C4mRestfulDocumentsResource.class.php
project/profiles/capacity4more/modules/c4m/user/c4m_user_notifications/c4m_user_notifications.module

https://issuetracker.amplexor.com/jira/browse/CFM-183

[CFM-183] Remove indirect document additions from the activity stream.

---

project/profiles/capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/services/request.js

https://issuetracker.amplexor.com/jira/browse/CFM-1476

[CFM-1476] [BUGFIX] validate categories is defined.

---

project/profiles/capacity4more/modules/c4m/og/c4m_og/c4m_og.module

https://issuetracker.amplexor.com/jira/browse/CFM-1554

[CFM-1554] Fixing form validate when the content author is site admin but not a group member

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_profile/c4m_user_profile.block.inc

https://issuetracker.amplexor.com/jira/browse/CFM-1204

[CFM-1204] Removing deleted groups from 'my groups' top bar list.

---

project/profiles/capacity4more/modules/c4m/og/c4m_og_vocab/c4m_og_vocab.module

https://issuetracker.amplexor.com/jira/browse/CFM-1316

[CFM-1316] Removing all og_vocab from the default taxonomy list.

---

project/profiles/capacity4more/behat/features/bootstrap/FeatureContext/Node.php
project/profiles/capacity4more/behat/features/group_wiki_pages.feature

https://issuetracker.amplexor.com/jira/browse/CFM-1241

[CFM-1241] Adding a behat test to check that GM can edit wiki page.

---

project/profiles/capacity4more/modules/c4m/content/c4m_content/c4m_content.module

https://issuetracker.amplexor.com/jira/browse/CFM-1049

[CFM-1049] Allow access to node/add to SA only.

---

project/profiles/capacity4more/modules/c4m/vocab/c4m_vocab_widget/c4m_vocab_widget.module

https://issuetracker.amplexor.com/jira/browse/CFM-1390

[CFM-1390] [BUGFIX] Send the correct field values to the app.

---

project/profiles/capacity4more/modules/c4m/og/c4m_og/c4m_og.module

https://issuetracker.amplexor.com/jira/browse/CFM-1554

[CFM-1554] Allow power users to delete any group content.

---

project/profiles/capacity4more/modules/c4m/features/c4m_features_homepage/c4m_features_homepage.views_default.inc

https://issuetracker.amplexor.com/jira/browse/CFM-924

[CFM-924] Remove deleted/draft projects from related projects view.

---

project/profiles/capacity4more/modules/c4m/features/c4m_features_homepage/plugins/content_types/my_groups/my-groups.tpl.php

https://issuetracker.amplexor.com/jira/browse/CFM-448
* Homepage:
* User profile:

Changing the title of the block to 'My Groups'.

---

project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/components/_forms.scss

https://issuetracker.amplexor.com/jira/browse/CFM-1207

[CFM-1207] Align types of discussions.

---

project/profiles/capacity4more/modules/c4m/comment/c4m_comment/c4m_comment.module
project/profiles/capacity4more/modules/c4m/user/c4m_user_admin/actions/c4m_user_admin.action.inc
project/profiles/capacity4more/modules/c4m/user/c4m_user_admin/c4m_user_admin.module
project/profiles/capacity4more/modules/c4m/user/c4m_user_admin/c4m_user_admin.views_default.inc
project/profiles/capacity4more/modules/c4m/user/c4m_user_profile/c4m_user_profile.features.field_base.inc
project/profiles/capacity4more/modules/c4m/user/c4m_user_profile/c4m_user_profile.features.field_instance.inc
project/profiles/capacity4more/modules/c4m/user/c4m_user_profile/c4m_user_profile.module
project/profiles/capacity4more/modules/c4m/user/c4m_user_profile/c4m_user_profile.pages.inc

https://issuetracker.amplexor.com/jira/browse/CFM-794

[CFM-794] Add deleted fields indication to the people view

---

project/profiles/capacity4more/behat/features/homepage.feature
project/profiles/capacity4more/modules/c4m/features/c4m_features_homepage/c4m_features_homepage.module

https://issuetracker.amplexor.com/jira/browse/CFM-1192

[CFM-1192-fix] Don't suggest groups for user that got no interests.

---

project/profiles/capacity4more/modules/c4m/search/c4m_search_filter/includes/c4m_search_filter.form.inc

https://issuetracker.amplexor.com/jira/browse/CFM-1571

[CFM-1571] Removing the projects filter on the events overview.

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_og/c4m_user_og.module

https://issuetracker.amplexor.com/jira/browse/CFM-1564

[CFM-1564] Display the memberships requests action link to all power users on all groups.

---

project/profiles/capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/directives/documents/quickPostDocuments.js
project/profiles/capacity4more/modules/c4m/restful/c4m_restful_quick_post/templates/quick-post-form.tpl.php
project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/base/_settings.scss
project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/components/_quickpost.scss

https://issuetracker.amplexor.com/jira/browse/CFM-940

[CFM-940] Adjust QP form for accessibility.

---

project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/components/_quickpost.scss

https://issuetracker.amplexor.com/jira/browse/CFM-938

[CFM-938] Fixing the related documents styling in the quickpost.

---

config/make/og.make

https://issuetracker.amplexor.com/jira/browse/CFM-1544

[CFM-1544] Adding a patch to fix the og_membership_access().

---

project/profiles/capacity4more/modules/c4m/message/c4m_message/c4m_message.features.inc
project/profiles/capacity4more/modules/c4m/message/c4m_message/c4m_message.module
project/profiles/capacity4more/modules/c4m/message/c4m_message/c4m_message.strongarm.inc
project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/components/_activity_stream.scss

https://issuetracker.amplexor.com/jira/browse/CFM-1077

[CFM-1077] Update the display of comments under activity stream.

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_notifications/includes/c4m_user_notifications_handlers.inc

https://issuetracker.amplexor.com/jira/browse/CFM-1535

[CFM-1535-fix] Don't notify admin that has demoted himself.

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_og/c4m_user_og.module

https://issuetracker.amplexor.com/jira/browse/CFM-1289

[CFM-1289] Replacing the icon of edit a membership.

---

project/profiles/capacity4more/behat/features/homepage.feature
project/profiles/capacity4more/modules/c4m/content/c4m_content/c4m_content.module
project/profiles/capacity4more/modules/c4m/features_og/c4m_features_og_events/c4m_features_og_events.module
project/profiles/capacity4more/modules/c4m/features_og/c4m_features_og_events/plugins/content_types/upcoming_events/upcoming_events.inc
project/profiles/capacity4more/modules/c4m/features_og/c4m_features_og_events/plugins/content_types/upcoming_events/upcoming_events.tpl.php

https://issuetracker.amplexor.com/jira/browse/CFM-1571

[CFM-1571] Fixing the upcoming events block on homepage.

---

project/profiles/capacity4more/modules/c4m/admin/c4m_admin/c4m_admin.module
project/profiles/capacity4more/modules/c4m/restful/c4m_restful_quick_post/c4m_restful_quick_post.module

https://issuetracker.amplexor.com/jira/browse/CFM-159

[CFM-159 Changing the theme of admin/people/create to kapablo.

---

project/profiles/capacity4more/modules/c4m/og/c4m_og_invite_visitors/c4m_og_invite_visitors.module

https://issuetracker.amplexor.com/jira/browse/CFM-546

[CFM-546-fix]  During invite visitor flow, issue notification to admins only when user becomes active.

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_profile/c4m_user_profile.block.inc

https://issuetracker.amplexor.com/jira/browse/CFM-1204

[CFM-1204] [BUGFIX] sort groups under top bar my groups by membership.

---

project/profiles/capacity4more/modules/c4m/content/c4m_content_document/c4m_content_document.module

https://issuetracker.amplexor.com/jira/browse/CFM-183
also resolve:
- https://issuetracker.amplexor.com/jira/browse/CFM-1572

[CFM-183] Remove indirect document addition via library as well.

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_notifications/c4m_user_notifications.module

https://issuetracker.amplexor.com/jira/browse/CFM-481

[CFM-481] [BUGFIX] Send GO / GA notification on membership approval.

---

project/profiles/capacity4more/modules/c4m/user/c4m_user/c4m_user.features.user_permission.inc

https://issuetracker.amplexor.com/jira/browse/CFM-1316

[CFM-1316] Export administer taxonomy permission.

---

project/profiles/capacity4more/behat/features/homepage.feature
project/profiles/capacity4more/modules/c4m/features/c4m_features_homepage/c4m_features_homepage.module

https://issuetracker.amplexor.com/jira/browse/CFM-1061
Also resolves:
- https://issuetracker.amplexor.com/jira/browse/CFM-1060

[CFM-1061] Fixing the featured groups block on homepage.

---

project/profiles/capacity4more/modules/c4m/content/c4m_content_photo/c4m_content_photo.features.field_instance.inc
project/profiles/capacity4more/modules/c4m/og/c4m_og/c4m_og.module

https://issuetracker.amplexor.com/jira/browse/CFM-1554
1. Avoid using Mail format.
2. Set formats order to : 
-  'default_html', 
-  'filtered_html',
-  'full_html',
-  'plain_text.
3. Allocate correct permissions to Node Gallery API features and gallery content types.

[CFM-1554-fix] Photo c4m_body field configuration && Node Gallery API access

---

project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/states/_activity_global.scss

https://issuetracker.amplexor.com/jira/browse/CFM-1439

[CFM-1439] Hide the quick post when JS is not enabled.

---

project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/components/_activity_stream.scss

https://issuetracker.amplexor.com/jira/browse/CFM-1138

[CFM-1138] Remove title of fallback js activity stream.

---

project/profiles/capacity4more/modules/c4m/og/c4m_og/c4m_og.module

https://issuetracker.amplexor.com/jira/browse/CFM-1575

[CFM-1575] Allow author of group content to be anonymous.

---

project/profiles/capacity4more/behat/features/bootstrap/FeatureContext/Group.php
project/profiles/capacity4more/modules/c4m/og/c4m_og/c4m_og.access.inc

https://issuetracker.amplexor.com/jira/browse/CFM-1565

[CFM-1565] Validate restricted group.

---

project/profiles/capacity4more/modules/c4m/content/c4m_content/c4m_content.module

https://issuetracker.amplexor.com/jira/browse/CFM-1226

[CFM-1226] Allow power users to create revisions.

---

project/profiles/capacity4more/modules/c4m/content/c4m_content_document/c4m_content_document.ds.inc

https://issuetracker.amplexor.com/jira/browse/CFM-1137

[CFM-1137] Adding the download counter to all document view modes.

---

project/profiles/capacity4more/modules/c4m/content/c4m_content/c4m_content.module
project/profiles/capacity4more/modules/c4m/content/c4m_content_news/c4m_content_news.ds.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_news/c4m_content_news.features.field_instance.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_news/c4m_content_news.field_group.inc
project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/components/_blocks.scss

https://issuetracker.amplexor.com/jira/browse/CFM-1287

[CFM-1287] Fixing news content type issues.

---

project/profiles/capacity4more/modules/c4m/features/c4m_features_homepage/plugins/content_types/my_groups/my_groups.inc

https://issuetracker.amplexor.com/jira/browse/CFM-446

[CFM-446] [BUGFIX] logic of show more button on my groups block.

---

project/profiles/capacity4more/modules/c4m/search/c4m_search_filter/includes/c4m_search_filter.form.inc

https://issuetracker.amplexor.com/jira/browse/CFM-1078

[CFM-1078] Adding the my projects filter on the projects overview.

---

project/profiles/capacity4more/modules/c4m/og/c4m_og/c4m_og.module

https://issuetracker.amplexor.com/jira/browse/CFM-1248

[CFM-1248] Editing content author - fix autocomplete

---

project/profiles/capacity4more/modules/c4m/content/c4m_content_photo/c4m_content_photo.ds.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_photo/c4m_content_photo.features.field_instance.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_photo/c4m_content_photo.strongarm.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_photoalbum/c4m_content_photoalbum.ds.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_photoalbum/c4m_content_photoalbum.features.field_instance.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_photoalbum/c4m_content_photoalbum.strongarm.inc

https://issuetracker.amplexor.com/jira/browse/CFM-1213

[CFM-1213] Adding the stats + highlight to the teaser view modes for photo and photoalbum

---

project/profiles/capacity4more/modules/c4m/features/c4m_features_homepage/c4m_features_homepage.module
project/profiles/capacity4more/modules/c4m/features/c4m_features_homepage/c4m_features_homepage.pages_default.inc
project/profiles/capacity4more/modules/c4m/features/c4m_features_homepage/c4m_features_homepage.views_default.inc
project/profiles/capacity4more/modules/c4m/features/c4m_features_homepage/plugins/content_types/c4m_suggested_groups/c4m_suggested_groups.inc
project/profiles/capacity4more/modules/c4m/features/c4m_features_homepage/plugins/content_types/c4m_suggested_projects/c4m_suggested_projects.inc
project/profiles/capacity4more/modules/c4m/features/c4m_features_homepage/plugins/content_types/c4m_suggested_projects/c4m_suggested_projects.tpl.php

https://issuetracker.amplexor.com/jira/browse/CFM-1198
Also resolve:
- https://issuetracker.amplexor.com/jira/browse/CFM-1062

[CFM-1198] Adding suggested projects to the homepage.

---

project/profiles/capacity4more/modules/c4m/og/c4m_og/c4m_og.features.og_features_permission.inc
project/profiles/capacity4more/modules/c4m/restful/c4m_restful/plugins/restful/C4mRestfulEntityBaseTaxonomyTerm.class.php

https://issuetracker.amplexor.com/jira/browse/CFM-1286

[CFM-1286] [BUGFIX] Allow free tags on projects events.

---

project/profiles/capacity4more/modules/c4m/restful/c4m_restful/plugins/restful/node/discussions/1.0/C4mRestfulDiscussionsResource.class.php
project/profiles/capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/controllers/main.js
project/profiles/capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/services/request.js

https://issuetracker.amplexor.com/jira/browse/CFM-1224

[CFM-1224] Activating the notifications checkbox on the quickpost.

---

project/profiles/capacity4more/modules/c4m/ds/c4m_ds/includes/c4m_ds.theme.node.inc

https://issuetracker.amplexor.com/jira/browse/CFM-1571

[CFM-1571] Remove the highlight button from the block list view mode.

---

project/profiles/capacity4more/modules/c4m/og/c4m_og/c4m_og.module

https://issuetracker.amplexor.com/jira/browse/CFM-1241

[CFM-1241] Allow GM to unpublish and publish an allowed wiki page.

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_og/c4m_user_og.module
project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/components/_group_dashboard.scss

https://issuetracker.amplexor.com/jira/browse/CFM-1206

[CFM-1206] Group CTA fixes.

---

project/profiles/capacity4more/modules/c4m/content/c4m_content_group/c4m_content_group.module

https://issuetracker.amplexor.com/jira/browse/CFM-1146

[CFM-1146] Adding space between group administrators.

---

project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/components/_header.scss

https://issuetracker.amplexor.com/jira/browse/CFM-1134

[CFM-1134] Hide the background banner on the header.

---

project/profiles/capacity4more/modules/c4m/features/c4m_features_homepage/c4m_features_homepage.views_default.inc
project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/components/_projects.scss
project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/components/_views.scss

https://issuetracker.amplexor.com/jira/browse/CFM-924

[CFM-924-fix] Related groups/projects views CSS adjustments & related projects view filtering.

---

project/profiles/capacity4more/behat/features/homepage.feature
project/profiles/capacity4more/modules/c4m/ds/c4m_ds/c4m_ds.module
project/profiles/capacity4more/modules/c4m/ds/c4m_ds/includes/c4m_ds.theme.user.inc
project/profiles/capacity4more/modules/c4m/features/c4m_features_homepage/c4m_features_homepage.pages_default.inc
project/profiles/capacity4more/modules/c4m/features/c4m_features_homepage/plugins/content_types/my_projects/my-projects.tpl.php
project/profiles/capacity4more/modules/c4m/features/c4m_features_homepage/plugins/content_types/my_projects/my_projects.inc
project/profiles/capacity4more/modules/c4m/user/c4m_user_profile/c4m_user_profile.block.inc
project/profiles/capacity4more/modules/c4m/user/c4m_user_profile/c4m_user_profile.ds.inc
project/profiles/capacity4more/modules/c4m/user/c4m_user_profile/c4m_user_profile.module
project/profiles/capacity4more/modules/c4m/user/c4m_user_profile/templates/my-profile-projects.tpl.php
project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/states/_full.scss

Homepage block:
Profile block:

CFM-1264: Add "my project" blocks on homepage and profile

---

project/profiles/capacity4more/modules/c4m/content/c4m_content_project/c4m_content_project.module
project/profiles/capacity4more/modules/c4m/features_og/c4m_features_og_search/c4m_features_og_search.module
project/profiles/capacity4more/modules/c4m/og/c4m_og/c4m_og.module
project/profiles/capacity4more/modules/c4m/search/c4m_search_og/c4m_search_og.blocks.inc
project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/components/_projects.scss

CFM-1151: Enable project/programme search system block.

---

project/profiles/capacity4more/modules/c4m/vocab/c4m_vocab_date/c4m_vocab_date.features.taxonomy.inc
project/profiles/capacity4more/modules/c4m/vocab/c4m_vocab_document_type/c4m_vocab_document_type.features.taxonomy.inc
project/profiles/capacity4more/modules/c4m/vocab/c4m_vocab_geo/c4m_vocab_geo.features.taxonomy.inc
project/profiles/capacity4more/modules/c4m/vocab/c4m_vocab_language/c4m_vocab_language.features.taxonomy.inc
project/profiles/capacity4more/modules/c4m/vocab/c4m_vocab_theme/c4m_vocab_theme.features.taxonomy.inc
project/profiles/capacity4more/modules/c4m/vocab/c4m_vocab_topic/c4m_vocab_topic.features.taxonomy.inc

Small fix for the vocabularies export. So that they don't appear as overridden.

Update vocabularies features export.

---

project/profiles/capacity4more/behat/features/bootstrap/FeatureContext/QuickPost.php
project/profiles/capacity4more/behat/features/bootstrap/FeatureContext/Wait.php
project/profiles/capacity4more/behat/features/quick_post.feature
project/profiles/capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/controllers/main.js
project/profiles/capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/directives/list-terms/list-terms.html
project/profiles/capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/directives/list-terms/list-terms.js
project/profiles/capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/services/request.js
project/profiles/capacity4more/modules/c4m/restful/c4m_restful_quick_post/templates/quick-post-form.tpl.php

https://issuetracker.amplexor.com/jira/browse/CFM-207

[CFM-207] quickpost fixes

---

project/profiles/capacity4more/modules/c4m/features/c4m_features_overview_events/c4m_features_overview_events.context.inc
project/profiles/capacity4more/modules/c4m/features/c4m_features_overview_events/c4m_features_overview_events.module
project/profiles/capacity4more/modules/c4m/features/c4m_features_overview_events/c4m_features_overview_events.views_default.inc
project/profiles/capacity4more/modules/c4m/features/c4m_features_overview_events/includes/c4m_features_overview_events.block.inc
project/profiles/capacity4more/modules/c4m/features_og/c4m_features_og_events/c4m_features_og_events.module
project/profiles/capacity4more/modules/c4m/features_og/c4m_features_og_events/includes/c4m_features_og_events.block.inc
project/profiles/capacity4more/modules/c4m/helper/c4m_helper_entity/c4m_helper_entity.module

https://issuetracker.amplexor.com/jira/browse/CFM-684

[CFM-684] Fixing titles and number of items on the events overviews.

---

project/profiles/capacity4more/behat/features/unified_workflow.feature
project/profiles/capacity4more/modules/c4m/comment/c4m_comment/c4m_comment.module
project/profiles/capacity4more/modules/c4m/user/c4m_user_og/c4m_user_og.module

https://issuetracker.amplexor.com/jira/browse/CFM-861

[CFM-861] Fixing rejects

---

project/profiles/capacity4more/behat/features/quick_post.feature
project/profiles/capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/directives/bundle-select/bundle-select.js
project/profiles/capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/directives/calendar/calendar.js
project/profiles/capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/directives/documents/documents.html
project/profiles/capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/directives/documents/documents.js
project/profiles/capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/directives/documents/quickPostDocuments.js
project/profiles/capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/directives/group-categories/group-categories.js
project/profiles/capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/directives/list-terms/list-terms.html
project/profiles/capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/directives/location/location.js
project/profiles/capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/directives/types/types.html
project/profiles/capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/directives/types/types.js
project/profiles/capacity4more/modules/c4m/restful/c4m_restful_quick_post/templates/quick-post-form.tpl.php

https://issuetracker.amplexor.com/jira/browse/CFM-940

[CFM-940] Adding title attribute + BUGFIX of the attachment files.

---

project/profiles/capacity4more/modules/c4m/restful/c4m_restful/plugins/restful/node/discussions/1.0/C4mRestfulDiscussionsResource.class.php

https://issuetracker.amplexor.com/jira/browse/CFM-207

[CFM-207] [BUGFIX] when creating a post via quick post, the format of the body field should be default_html.

---

project/profiles/capacity4more/modules/c4m/content/c4m_content_photo/c4m_content_photo.features.field_instance.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_photoalbum/c4m_content_photoalbum.features.field_instance.inc
project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/components/_views.scss

https://issuetracker.amplexor.com/jira/browse/CFM-1255

[CFM-1255-fix] Configure photo and photoalbum CTs for group dashboard highlight

---

project/profiles/capacity4more/behat/features/users.feature
project/profiles/capacity4more/modules/c4m/user/c4m_user_profile/c4m_user_profile.module

https://issuetracker.amplexor.com/jira/browse/CFM-159

[CFM-159-fx] Create user by admin form update - do not allow to choose role.

---

project/profiles/capacity4more/behat/features/bootstrap/FeatureContext/Node.php
project/profiles/capacity4more/behat/features/quick_post.feature

https://issuetracker.amplexor.com/jira/browse/CFM-207

[CFM-207] Testing the cody format of a discussion created via the quick post.

---

project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/components/_forms.scss

https://issuetracker.amplexor.com/jira/browse/CFM-1344

[CFM-1344-fix] Do not apply bold font on control-label at node form

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_profile/c4m_user_profile.module

https://issuetracker.amplexor.com/jira/browse/CFM-486

[CFM-486-fix] Verify 'email-change confirmation' mails format is defined per user profile.

---

project/profiles/capacity4more/modules/c4m/content/c4m_content/c4m_content.module

https://issuetracker.amplexor.com/jira/browse/CFM-1285

[CFM-1285-fix] After deleting group content, redirect to group homepage.

---

project/profiles/capacity4more/behat/features/bootstrap/FeatureContext/Node.php
project/profiles/capacity4more/modules/c4m/message/c4m_message/c4m_message.module

https://issuetracker.amplexor.com/jira/browse/CFM-1226

Do not create an activity stream message when user is not creating a new revision.

---

project/profiles/capacity4more/modules/c4m/message/c4m_message/c4m_message.module

https://issuetracker.amplexor.com/jira/browse/CFM-861
https://issuetracker.amplexor.com/jira/browse/CFM-1194

[CFM-861-fix] Activity stream items view, for restricted groups.

---

project/profiles/capacity4more/behat/features/quick_post.feature
project/profiles/capacity4more/modules/c4m/content/c4m_content/c4m_content.module

https://issuetracker.amplexor.com/jira/browse/CFM-207

[CFM-207] Adding a message to the user regarding the draft entity.

---

config/make/og.make
config/patches/og_ui-invited_members_count_overview.patch

https://issuetracker.amplexor.com/jira/browse/CFM-1561

[CFM-1561] Splitting between the total members of a group and the total invited members.

---

project/profiles/capacity4more/behat/features/bootstrap/FeatureContext/GroupDashboard.php
project/profiles/capacity4more/behat/features/bootstrap/FeatureContext/Highlights.php
project/profiles/capacity4more/behat/features/projects.feature
project/profiles/capacity4more/modules/c4m/user/c4m_user_og/c4m_user_og.module
project/profiles/capacity4more/modules/c4m/user/c4m_user_og/templates/c4m_group_manage_cta.tpl.php

https://issuetracker.amplexor.com/jira/browse/CFM-1307

[CFM-1307] Add project highlight icon to project manage cta block.

---

project/profiles/capacity4more/modules/c4m/features_og/c4m_features_og_highlights/c4m_features_og_highlights.views_default.inc
project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/components/_group_dashboard.scss

https://issuetracker.amplexor.com/jira/browse/CFM-1255

[CFM-1255] Removing the pager from the highlight features on the group dashboard.

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_notifications/c4m_user_notifications.module

https://issuetracker.amplexor.com/jira/browse/CFM-546

[CFM-546-fix] Verify MT14 sent, when admin sets membership to active 

---

project/profiles/capacity4more/behat/features/bootstrap/FeatureContext.php
project/profiles/capacity4more/behat/features/bootstrap/FeatureContext/Project.php
project/profiles/capacity4more/behat/features/projects.feature
project/profiles/capacity4more/modules/c4m/content/c4m_content/c4m_content.module
project/profiles/capacity4more/modules/c4m/content/c4m_content_group/c4m_content_group.module
project/profiles/capacity4more/modules/c4m/features_og/c4m_features_og_members/c4m_features_og_members.module
project/profiles/capacity4more/modules/c4m/message/c4m_message/c4m_message.module
project/profiles/capacity4more/modules/c4m/og/c4m_og/c4m_og.access.inc
project/profiles/capacity4more/modules/c4m/og/c4m_og/c4m_og.module
project/profiles/capacity4more/modules/c4m/user/c4m_user_profile/c4m_user_profile.block.inc

https://issuetracker.amplexor.com/jira/browse/CFM-1332
This PR replaces #1603

[CFM-1332] Configure project permissions.

---

project/profiles/capacity4more/modules/c4m/message/c4m_message/c4m_message.module
project/profiles/capacity4more/modules/c4m/user/c4m_user_notifications/includes/c4m_user_notifications_handlers.inc

Replace callback function for message params, with their resolved value.

---

project/profiles/capacity4more/modules/c4m/content/c4m_content_wiki_page/c4m_content_wiki_page.module

https://issuetracker.amplexor.com/jira/browse/CFM-966

[CFM-966] Fixing the wiki page revision for GO and GA.

---

project/profiles/capacity4more/modules/c4m/message/c4m_message/c4m_message.module

@soniCaH 
Here is a fix to #1614

[BUGFIX] Validate offset.

---

project/profiles/capacity4more/modules/c4m/features/c4m_features_overview_events/c4m_features_overview_events.module
project/profiles/capacity4more/modules/c4m/features/c4m_features_overview_events/c4m_features_overview_events.views_default.inc
project/profiles/capacity4more/modules/c4m/features_og/c4m_features_og_events/c4m_features_og_events.module
project/profiles/capacity4more/modules/c4m/features_og/c4m_features_og_events/c4m_features_og_events.views_default.inc

https://issuetracker.amplexor.com/jira/browse/CFM-1067

[CFM-1067] titles + sort fixes

---

config/make/og.make
config/patches/og_invite-decline_message.patch
project/profiles/capacity4more/modules/c4m/og/c4m_og/c4m_og.module
project/profiles/capacity4more/modules/c4m/og/c4m_og_invite_users/c4m_og_invite_users.module
project/profiles/capacity4more/modules/c4m/og/c4m_og_invite_visitors/c4m_og_invite_visitors.module
project/profiles/capacity4more/modules/c4m/user/c4m_user_og/c4m_user_og.module

https://issuetracker.amplexor.com/jira/browse/CFM-1561
- Fixed the decline message by adding a patch.
- Fixed the title and the button on the registration form.
- Fixed a bug when a user try to invite a member to a specific group but withing a context of a different group (can happen if changing the url explicitly).
- Removed the _always decline_ option since it has a [bug](https://www.drupal.org/node/2320373) on the contrib itself.

[CFM-1561] Fixing invite issues.

---

project/profiles/capacity4more/modules/c4m/features/c4m_features_overview_events/c4m_features_overview_events.module
project/profiles/capacity4more/modules/c4m/features_og/c4m_features_og_events/c4m_features_og_events.module

https://issuetracker.amplexor.com/jira/browse/CFM-1067

[CFM-1067] [BUGFIX] Events sort dropdown.

---

project/profiles/capacity4more/modules/c4m/features_og/c4m_features_og_members/c4m_features_og_members.admin.inc

https://issuetracker.amplexor.com/jira/browse/CFM-1586

[CFM-1586] Block membership instead of removing it.

---

project/profiles/capacity4more/modules/c4m/content/c4m_content/c4m_content.module

https://issuetracker.amplexor.com/jira/browse/CFM-1583

[CFM-1583] Adding the "Send Notification" checkbox to the article form.

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_notifications/includes/c4m_user_notifications_handlers.inc

https://issuetracker.amplexor.com/jira/browse/CFM-1585

[CFM-1585] Update content notifications issues.

---

project/profiles/capacity4more/modules/c4m/content/c4m_content/c4m_content.module
project/profiles/capacity4more/modules/c4m/content/c4m_content_project/c4m_content_project.block.inc
project/profiles/capacity4more/modules/c4m/features/c4m_features_footer/includes/c4m_features_footer.theme.inc

https://issuetracker.amplexor.com/jira/browse/CFM-492

[CFM-492-fix] Add AJAX library and fix links.

---

project/profiles/capacity4more/modules/c4m/message/c4m_message/c4m_message.module

https://issuetracker.amplexor.com/jira/browse/CFM-966

[CFM-966-fix] Do not create AS for Draft content.

---

project/profiles/capacity4more/modules/c4m/og/c4m_og_invite_visitors/c4m_og_invite_visitors.module

https://issuetracker.amplexor.com/jira/browse/CFM-349

[CFM-349-fix] Generate join token with absolute path.

---

project/profiles/capacity4more/modules/c4m/content/c4m_content/c4m_content.module

Another fix for https://issuetracker.amplexor.com/jira/browse/CFM-492.

[CFM-492-fix] Make sure toggle link includes purl, so we get the OG context.

---

project/profiles/capacity4more/modules/c4m/user/c4m_user/actions/c4m_user_contact_multiple.action.inc
project/profiles/capacity4more/modules/c4m/user/c4m_user/includes/c4m_user.theme.inc

https://issuetracker.amplexor.com/jira/browse/CFM-406

[CFM 406-fix] Fix contact forms redirect links.

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_subscribe/c4m_user_subscribe.module

https://issuetracker.amplexor.com/jira/browse/CFM-47.

[CFM-47-fix] When admin approves membership, subscribe the user that was approved.

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_subscribe/c4m_user_subscribe.module

https://issuetracker.amplexor.com/jira/browse/CFM-286

[CFM-286-fix] Subscribe entity owner on hook entity insert.

---

project/profiles/capacity4more/modules/c4m/content/c4m_content_photo/c4m_content_photo.ds.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_photo/c4m_content_photo.features.field_instance.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_photoalbum/c4m_content_photoalbum.ds.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_photoalbum/c4m_content_photoalbum.features.field_instance.inc

https://issuetracker.amplexor.com/jira/browse/CFM-671

[CFM-671-fix] Add missing fields to photo and photo album teaser_group displays.

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_subscribe/c4m_user_subscribe.module

https://issuetracker.amplexor.com/jira/browse/CFM-47

[CFM-47-fix] Make sure we flag only user memberships.

---

project/profiles/capacity4more/modules/c4m/content/c4m_content_project/c4m_content_project.module
project/profiles/capacity4more/modules/c4m/content/c4m_content_wiki_page/includes/c4m_content_wiki_page.theme.inc
project/profiles/capacity4more/modules/c4m/features_og/c4m_features_og_wiki/includes/c4m_features_og_wiki.theme.inc
project/profiles/capacity4more/modules/c4m/restful/c4m_restful_quick_post/c4m_restful_quick_post.module
project/profiles/capacity4more/modules/c4m/user/c4m_user/actions/c4m_user_contact_multiple.action.inc
project/profiles/capacity4more/modules/c4m/user/c4m_user_og/c4m_user_og.module

https://issuetracker.amplexor.com/jira/browse/CFM-487

[CFM-487-fix] Read-only group actions.

---

project/profiles/capacity4more/modules/c4m/helper/c4m_helper_entity/c4m_helper_entity.module

https://issuetracker.amplexor.com/jira/browse/CFM-684

[CFM-684-fix] Modify the way we get total results count for events views.

---

project/profiles/capacity4more/modules/c4m/og/c4m_og_vocab/templates/c4m_categories_vocab_widget.tpl.php
project/profiles/capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/filters/terms-filter.js
project/profiles/capacity4more/modules/c4m/vocab/c4m_vocab_widget/c4m_vocab_widget.module
project/profiles/capacity4more/modules/c4m/vocab/c4m_vocab_widget/templates/c4m_vocab_widget.tpl.php

https://issuetracker.amplexor.com/jira/browse/CFM-630
https://issuetracker.amplexor.com/jira/browse/CFM-1624

[CFM-630-fix] Sort vocab widget terms by 'weight'.

---

project/profiles/capacity4more/modules/c4m/og/c4m_og/c4m_og.module
project/profiles/capacity4more/modules/c4m/user/c4m_user_notifications/c4m_user_notifications.module

Redirect to the group dashboard + don’t send message about demoted administration rights to the new owner.

CFM-135: Redirect to the group dashboard + don’t send message

---

project/profiles/capacity4more/modules/c4m/message/c4m_message/c4m_message.features.inc

https://issuetracker.amplexor.com/jira/browse/CFM-422

[CFM-422-fix] Set node_insert message format to 'mail'.

---

project/profiles/capacity4more/modules/c4m/user/c4m_user/includes/c4m_user.theme.inc

https://issuetracker.amplexor.com/jira/browse/CFM-406

[CFM-406-fix] Fix contact single user redirect link.

---

project/profiles/capacity4more/modules/c4m/og/c4m_og_purl/c4m_og_purl.module

https://issuetracker.amplexor.com/jira/browse/CFM-624

[CFM-624-fix] Redirect path when updating group purl.

---

project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/base/_mixins.scss
project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/components/_views.scss

https://issuetracker.amplexor.com/jira/browse/CFM-239

[CFM-239-fix] Related groups/projects - margins and borders.

---

project/profiles/capacity4more/modules/c4m/content/c4m_content_photoalbum/c4m_content_photoalbum.module

https://issuetracker.amplexor.com/jira/browse/CFM-642

[CFM-642-dix] Adding photo to photo album.

---

project/profiles/capacity4more/modules/c4m/features_og/c4m_features_og_wiki/includes/c4m_features_og_wiki.inc

https://issuetracker.amplexor.com/jira/browse/CFM-535

[CFM-535-fix] Show 'add wiki' button, as if there're no wiki pages, even if unpublished wiki pages exist.

---

project/profiles/capacity4more/themes/c4m/kapablo/build/src/javascripts/kapablo.js
project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/states/_full.scss

- Wiki sidebar collapse/expand (FIXED)

CFM-693: Wiki fixes

---

project/profiles/capacity4more/modules/c4m/og/c4m_og/c4m_og.module

https://issuetracker.amplexor.com/jira/browse/CFM-374

[CFM-374-fix] Do not update group content realms when group request is approved/rejected.

---

project/profiles/capacity4more/modules/c4m/restful/c4m_restful_quick_post/c4m_restful_quick_post.module

https://issuetracker.amplexor.com/jira/browse/CFM-374

[CFM-374-fix] Hide QP at 'pending' group, if user is site admin.

---

project/profiles/capacity4more/modules/c4m/message/c4m_message/c4m_message.features.inc

https://issuetracker.amplexor.com/jira/browse/CFM-263

[CFM-263-fix] Set format of messages body to 'mail'.

---

project/profiles/capacity4more/modules/c4m/mail/c4m_mail/messages/user/user_mail_status_activated_body.html

https://issuetracker.amplexor.com/jira/browse/CFM-160

[CFM-160-fix] MT3 help section link.

---

project/profiles/capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/controllers/main.js
project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/components/_quickpost.scss

https://issuetracker.amplexor.com/jira/browse/CFM-1632

[CFM-1632] Emphasize selected discussion type at QP.

---

config/make/minimal.make

https://issuetracker.amplexor.com/jira/browse/CFM-1590

[CFM-1590] Adding a patch for ctools which should handle yet registered classes.

---

project/profiles/capacity4more/modules/c4m/content/c4m_content_news/c4m_content_news.ds.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_news/c4m_content_news.info

https://issuetracker.amplexor.com/jira/browse/CFM-654

[CFM-654-fix] Adjust News Comment Displays.

---

project/profiles/capacity4more/modules/c4m/ds/c4m_ds/includes/c4m_ds.theme.node.inc

https://issuetracker.amplexor.com/jira/browse/CFM-684

[CFM-684-fix] Calendar icon date.

---

project/profiles/capacity4more/modules/c4m/content/c4m_content_news/c4m_content_news.features.field_instance.inc

https://issuetracker.amplexor.com/jira/browse/CFM-1287

[CFM-1287] Body field of News content type should be required.

---

project/profiles/capacity4more/modules/c4m/features/c4m_features_social/c4m_features_social.module

https://issuetracker.amplexor.com/jira/browse/CFM-403

[CFM-403-fix] Share icons for private/restricted groups.

---

project/profiles/capacity4more/behat/behat.yml
project/profiles/capacity4more/behat/features/group_dashboard.feature
project/profiles/capacity4more/modules/c4m/content/c4m_content_discussion/c4m_content_discussion.ds.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_document/c4m_content_document.ds.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_event/c4m_content_event.ds.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_photo/c4m_content_photo.ds.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_photoalbum/c4m_content_photoalbum.ds.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_wiki_page/c4m_content_wiki_page.ds.inc

https://issuetracker.amplexor.com/jira/browse/CFM-671

[CMF-671-fix] Set title to be a link for all content types that got 'highlight_list' display mode.

---

project/profiles/capacity4more/behat/features/bootstrap/FeatureContext/User.php
project/profiles/capacity4more/behat/features/users.feature
project/profiles/capacity4more/modules/c4m/message/c4m_message/c4m_message.module
project/profiles/capacity4more/modules/c4m/user/c4m_user_profile/c4m_user_profile.module

https://issuetracker.amplexor.com/jira/browse/CFM-263

[CFM-263] Fixing unsubscribe hash creation.

---

project/profiles/capacity4more/modules/c4m/content/c4m_content_article/c4m_content_article.features.field_instance.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_group/c4m_content_group.features.field_instance.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_project/c4m_content_project.features.field_instance.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_topic/c4m_content_topic.features.field_instance.inc
project/profiles/capacity4more/modules/c4m/field/c4m_field_banner/c4m_field_banner.features.field_base.inc

https://issuetracker.amplexor.com/jira/browse/CFM-292

[CFM-292-fix] Set c4m_banner scheme as public.

---

project/profiles/capacity4more/modules/c4m/user/c4m_user/c4m_user.module

Fixes resulted from: https://scrutinizer-ci.com/g/capacity4dev/capacity4more/code-structure/develop/operation/project%2Fprofiles%2Fcapacity4more%2Fmodules%2Fc4m%2Fuser%2Fc4m_user%2Fc4m_user.module%3A%3Ac4m_user_update_information.

Scrutenizer fixes on `c4m_user.module` (scored F).

---

project/profiles/capacity4more/capacity4more.install

https://issuetracker.amplexor.com/jira/browse/CFM-1666

[CFM-1666] Speed up clearing caches

---

project/profiles/capacity4more/modules/c4m/og/c4m_og/c4m_og.module

CAPFDEV-1243: Fix permission for group invitations overview.

---

project/profiles/capacity4more/modules/c4m/wysiwyg/c4m_wysiwyg_ckeditor/c4m_wysiwyg_ckeditor.features.filter.inc
project/profiles/capacity4more/modules/c4m/wysiwyg/c4m_wysiwyg_ckeditor/c4m_wysiwyg_ckeditor.info
project/profiles/capacity4more/modules/c4m/wysiwyg/c4m_wysiwyg_ckeditor/c4m_wysiwyg_ckeditor.module

CFDRMD-50: Cookie Consent Kit

---

project/profiles/capacity4more/modules/c4m/wysiwyg/c4m_wysiwyg_ckeditor/c4m_wysiwyg_ckeditor.module

Changed the way dom is rendered so it takes into account all the iframes from a page.

CFDRMD-50: Changed the way dom is rendered 

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_notifications/includes/c4m_user_notifications.notify_subscribe.inc
project/profiles/capacity4more/modules/c4m/user/c4m_user_subscribe/c4m_user_subscribe.module

Merge/review this branch before #1787 please.

CFDRMD-181: Subscribe users only to the "most specific" term in a hierarchy

---

project/profiles/capacity4more/themes/c4m/kapablo/build/src/javascripts/kapablo.js

CFDRMD-105: Fix - Submit button in registration form is not enabled after all required fields are filled in.

CFDRMD-105: Fix - Submit button in registration form.

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_notifications/includes/c4m_user_notifications.notify_subscribe.inc

Cherrypick from https://github.com/easme-web/capacity4more/pull/21.

EASME-50: Added check for body field before including it into the message

---

config/make/_core.make
config/make/administration.make
config/make/minimal.make
config/make/search.make
config/make/users.make
config/make/views.make
project/profiles/capacity4more/modules/c4m/og/c4m_og/c4m_og.install
project/profiles/capacity4more/modules/c4m/og/c4m_og/c4m_og.module
project/profiles/capacity4more/modules/c4m/og/c4m_og_purl/c4m_og_purl.module
project/profiles/capacity4more/modules/c4m/og/c4m_og_vocab/c4m_og_vocab.module

Reverts capacity4dev/capacity4more#1897

Revert "Update develop with latest master changes"
