capacity4more/capacity4more.info
capacity4more/modules/c4m/search/c4m_search_og/c4m_search_og.info
capacity4more/modules/c4m/search/c4m_search_og/c4m_search_og.module

Added an extra module (c4m_search_og) that adds the missing functionality when combining search_api & og_access.
That modules marks OG group content data as dirty when the access type of a group changes.
When the group access changes (og_access) the node_access data is rebuild for all nodes within that group. Rebuilding that data does not trigger a node_save. Search API does not know that the permissions, that are also indexed, should be re-indexed.
To fix this we alter the og_access batch set and add an extra set to mark all group content as dirty so search_api will pass it to the search engine for re-indexing.

CFD-278 : Group Access: Changing group access type (public/restricted/private) does not trigger reindex on group content

---

capacity4more/modules/c4m/features_og/c4m_features_og_events/c4m_features_og_events.module

There was a wrong field name used in the query (it's c4m_related_topic not c4m_related_topic**s**).
This caused WSOD due to Exceptions.
See #513

CFD-298 : Wrong variable name used in the query.

---

capacity4more/behat/features/homepage.feature
capacity4more/modules/c4m/content/c4m_content_group/c4m_content_group.ds.inc

#525 
This was added and styled, apparently not exported correctly.
* Fixed the export.
* Added a test to make sure it's always there.

CFD-319 : Homepage : group owner is missing in the my groups & suggested groups list

---

capacity4more/modules/c4m/features/c4m_features_overview_articles/c4m_features_overview_articles.context.inc
capacity4more/modules/c4m/features_og/c4m_features_og_members/c4m_features_og_members.context.inc

#582 
Voices & views "In the picture" banner:
People & members has a different "In the picture" banner:

CFD-415 : The in-the-picture block should not be visible in the Group members section.

---

capacity4more/themes/c4m/kapablo/sass/components/_facets.scss
capacity4more/themes/c4m/kapablo/theme/search.inc

Themed active facet links:
- added icons for expandable links
- added "x" to deactivate active facet link

CFD-419 theme active facet links

---

capacity4more/modules/c4m/content/c4m_content_article/c4m_content_article.features.field_instance.inc

It's possible to make the url optional:

CFD-420 Make the external contributor url optional

---

capacity4more/modules/c4m/content/c4m_content_wiki_page/c4m_content_wiki_page.module
capacity4more/modules/c4m/features_og/c4m_features_og_wiki/includes/c4m_features_og_wiki.theme.inc
capacity4more/modules/c4m/restful/c4m_restful_quick_post/c4m_restful_quick_post.module
capacity4more/themes/c4m/kapablo/sass/components/_forms.scss

#612 
* Added a button to add a new wiki page when there's none. (Only to group admins)
* Fixed the "Add a wiki" form vocabularies.
* Fixed checkboxes visibility in FF.
* Fixed error message on add wiki page form, For group admins.

CFD-336 : invalid vocabularies under page creation form + missing creation button.

---

capacity4more/capacity4more.info
capacity4more/modules/c4m/domain/c4m_domain/c4m_domain.api.php
capacity4more/modules/c4m/domain/c4m_domain/c4m_domain.info
capacity4more/modules/c4m/domain/c4m_domain/c4m_domain.install
capacity4more/modules/c4m/domain/c4m_domain/c4m_domain.module

Implemented new entity and admin overview for email domains: c4m_domain

CFD-394 CFD-395 Email domain entity and admin overview

---

capacity4more/modules/c4m/admin/c4m_admin_groups/c4m_admin_groups.module

Machine-name script creates an error when trying to get the ajax form after removing the previous image.
Creates an undefined object, added a small script to make sure machineName object is never undefined.

CFD-354 : Cannot upload a new banner/image once previous is removed

---

capacity4more/modules/c4m/admin/c4m_admin_groups/c4m_admin_groups.module

Follow up on #653
This will load the fix only when needed 
- Group add/edit form
- Project add/edit form

CFD-354 : Cannot upload a new banner/image once previous is removed - Fix

---

capacity4more/modules/c4m/restful/c4m_restful_quick_post/components/c4m-app/src/controllers/main.js

When no location is set in an event via quickpost, don't set a default (to Brussels)

CFD-349 - events without a location

---

capacity4more/modules/c4m/content/c4m_content_group/js/group-details.js
capacity4more/themes/c4m/kapablo/sass/components/_group_blocks.scss

The bootstrap collapse js wasn't being executed because the custom group details behavior used the same class name in the 'once' function and so prevented bootstrap

CFD-282 group page fieldset not collapse

---

capacity4more/modules/c4m/features_og/c4m_features_og_events/c4m_features_og_events.context.inc
capacity4more/modules/c4m/features_og/c4m_features_og_events/c4m_features_og_events.views_default.inc
capacity4more/themes/c4m/kapablo/sass/components/_event.scss
capacity4more/themes/c4m/kapablo/sass/components/_views.scss

Added 'Add an event' button in the header of the event overview page-view and removed the button from the upcomming-events block
Updated 'Add an event' button css for better layout
Rearanged weights of group events overview blocks so they come under the page content

CFD-331 Add 'Add an event' button in the header of the event overview

---

capacity4more/themes/c4m/kapablo/theme/menu.inc

Issue occurs when using bootstrap.js and AngularJS together
http://stackoverflow.com/a/28610640
Fix by adding:
$element['#localized_options']['attributes']['data-disabled'] = 'true';

CFD-481 Fix wiki dropdown on group homepage

---

capacity4more/behat/features/bootstrap/FeatureContext/Search.php
capacity4more/modules/c4m/features/c4m_features_overview_articles/c4m_features_overview_articles.views_default.inc
capacity4more/modules/c4m/features/c4m_features_overview_events/c4m_features_overview_events.views_default.inc
capacity4more/modules/c4m/features/c4m_features_overview_groups/c4m_features_overview_groups.views_default.inc
capacity4more/modules/c4m/features/c4m_features_overview_people/c4m_features_overview_people.views_default.inc
capacity4more/modules/c4m/features_og/c4m_features_og_discussions/c4m_features_og_discussions.views_default.inc
capacity4more/modules/c4m/features_og/c4m_features_og_documents/c4m_features_og_documents.views_default.inc
capacity4more/modules/c4m/features_og/c4m_features_og_events/c4m_features_og_events.views_default.inc
capacity4more/modules/c4m/features_og/c4m_features_og_members/c4m_features_og_members.views_default.inc
capacity4more/modules/c4m/search/c4m_search/c4m_search.features.inc
capacity4more/modules/c4m/search/c4m_search/c4m_search.module
capacity4more/themes/c4m/kapablo/sass/components/_views.scss

Show sort by relevance only when a search term is entered.
Make sort by relevance the default sort when a term is entered without a manual sort being selected.

CFD-507 Search : Show "order by relevance" only when a search term is entered

---

capacity4more/drupal-org.make

https://issuetracker.amplexor.com/jira/browse/CFD-329?focusedCommentId=211569&#comment-211569
This fixes Diane's comment.
It was actually a bug in the entity reference module, Applied a patch and it fixed it.
Created a group with special chars in the title:
And after the fix, in the "subgroup of" field:
In the admin allowed values:
Another example:

CFD-329 : formatting bug on vocabulary lists.

---

project/profiles/capacity4more/modules/c4m/features/c4m_features_homepage/c4m_features_homepage.module
project/profiles/capacity4more/modules/c4m/features/c4m_features_homepage/plugins/content_types/c4m_suggested_groups/c4m_suggested_groups.inc
project/profiles/capacity4more/modules/c4m/features/c4m_features_homepage/plugins/content_types/c4m_suggested_groups/c4m_suggested_groups.tpl.php

Updates the suggested groups block to display 5 items, order them alphabetically and send the user interests as default filters on the group page.
Issue: https://issuetracker.amplexor.com/jira/browse/CFM-1192

CFM-1192: Create view block to display suggested groups

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_profile/c4m_user_profile.module
project/profiles/capacity4more/modules/c4m/user/c4m_user_profile/c4m_user_profile.pages.inc

Adds new custom cancel method that disables the user and reassigns the content.
Previous PR: https://github.com/capacity4dev/capacity4more/pull/1091
Issue: https://issuetracker.amplexor.com/jira/browse/CFM-787
Pics: 
Confirmation to the user that it's disabled (default Drupal messages):
User listing shows Galileo as blocked:
The content appears as anonymous:

CFM-787: Create custom "leave" page

---

project/profiles/capacity4more/modules/c4m/user/c4m_user_og/c4m_user_og.module

Adds back the drupal_set_message that tells the user about the group membership.
Issue: https://issuetracker.amplexor.com/jira/browse/CFM-922
Seems that the changes from https://github.com/capacity4dev/capacity4more/pull/1064 are lost. New branch created to add them back.
Screenshot:

CFM-922: Show status message

---

project/profiles/capacity4more/behat/features/bootstrap/FeatureContext/Node.php
project/profiles/capacity4more/behat/features/content_form.feature
project/profiles/capacity4more/behat/features/group_discussions.feature
project/profiles/capacity4more/modules/c4m/content/c4m_content/c4m_content.module

Issue: https://issuetracker.amplexor.com/jira/browse/CFM-1244
Previous PR: https://github.com/capacity4dev/capacity4more/pull/1086
Screenshots:
Before, when editing a discussion, the unpublish button was gone:
After, when editing a discussion the unpublish button is there:
When editing a group or project, the unpublish button is still gone:

[CFM-1244] Remove unpublish button from groups/projects

---

project/profiles/capacity4more/modules/c4m/og/c4m_og/plugins/entityreference/selection/C4MSelectionHandler.class.php

Fixes issue on autocompletion of references to groups due to not passing the variables to the parent function.
Issue: https://issuetracker.amplexor.com/jira/browse/CFM-1047
Screenshot:

[CFM-1047] Group entity references fields not correctly autocompleting

---

project/profiles/capacity4more/modules/c4m/content/c4m_content_event/c4m_content_event.ds.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_event/c4m_content_event.features.field_instance.inc
project/profiles/capacity4more/modules/c4m/content/c4m_content_event/c4m_content_event.strongarm.inc
project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/components/_events.scss

Changed fields display order (moved `Group` from the right region to the footer) & and modified styling.
**JIRA**: https://issuetracker.amplexor.com/jira/browse/CFM-1066
**Mobile:**
**Tablet:**
**Desktop:**

[CFM-1066] Upcoming Events block theming

---

project/profiles/capacity4more/modules/c4m/content/c4m_content_group/c4m_content_group.module

Moves markup of the group admins to a theme suffix to ensure is added after the title.
Issue: https://issuetracker.amplexor.com/jira/browse/CFM-1148
Screenshots:

[CFM-1148] Fixes for group view modes

---

README.md

The necessary variables will be set before running the bash script.

Instructions for running Coder tests

---

project/profiles/capacity4more/behat/features/group_dashboard.feature
project/profiles/capacity4more/modules/c4m/user/c4m_user_og/c4m_user_og.module

Following the comment @soniCaH left on https://issuetracker.amplexor.com/jira/browse/CFM-1348
@anvmn found this bug.

[BUGFIX] Group notifications toggle link should not appear for non members of a group.

---

project/profiles/capacity4more/modules/c4m/og/c4m_og/c4m_og.module

https://issuetracker.amplexor.com/jira/browse/CFM-546
The problem was that owner was not included in groups admins list.

[CFM-546-fix] Make sure owner is included when selecting group admins

---

project/profiles/capacity4more/modules/c4m/user/c4m_user/includes/c4m_user.theme.inc

Don’t link if the user is not active 
+ fix link to user profile instead of content.

CFM-375: Don’t link if the user is not active 

---

project/profiles/capacity4more/modules/c4m/og/c4m_og/c4m_og.module

https://issuetracker.amplexor.com/jira/browse/CFM-666

[CFM-666-fix] Delete base_path() prefix at $path, when redirecting (drupal_goto()).

---

project/profiles/capacity4more/modules/c4m/admin/c4m_admin_groups/c4m_admin_groups.views_default.inc
project/profiles/capacity4more/modules/c4m/helper/c4m_helper_entity/c4m_helper_entity.module
project/profiles/capacity4more/modules/c4m/user/c4m_user_og/c4m_user_og.module

- Add the OG (active) state to the metrics query.
- Remove the members vs contributors statistic.

CFM-631: Fixes for groups export

---

project/profiles/capacity4more/modules/c4m/og/c4m_og/plugins/entityreference/selection/C4MOgSelectionHandler.class.php
project/profiles/capacity4more/modules/c4m/og/c4m_og/plugins/entityreference/selection/C4MSelectionHandler.class.php
project/profiles/capacity4more/themes/c4m/kapablo/build/src/stylesheets/components/_forms.scss

CFM-318 introduced some issues as both the "og_group_ref" and the "c4m_related_groups/projects" field bases were using the same base class to provide their autocomplete functionality.
In CFM-318 we set some more strict permissions, causing GO/GA could no longer create content in draft groups. This is now solved.

CFM-1650: Split related groups/projects and `og_group_ref` selectors.

---

project/profiles/capacity4more/modules/c4m/widgets/c4m_document_widget/c4m_document_widget.module

Increase the maxlength of c4d_document widget (entity reference) from 1024 (default) to 2500.

CAPFDEV-1227: Increase the maxlength of c4d_document widget.

---

config/make/og.make

Cherrypick from https://github.com/easme-web/capacity4more/pull/24.

EASME-53: Applied patch that fixes error from OG Vocab widget

---

ci/bin/install_solr.sh

Default version was switched to Drupal 8 version, since we are not in a Drupal environment when we download the module. Therefore the config folder in the installation instructions was changed and caused errors.

Pinpoint the solr version drush needs to download.
